  DSN SYSTEM(DB2P)
  DSN SYSTEM(DB2P)
  -START DB(SU0BP) SPACE(SU099*) ACCESS(RW)
  -START DB(SU0BP) SPACE(SU099*) ACCESS(RW)
  -START DB(AISERIES) SPACE(SU099*) ACCESS(RW)
  -START DB(AISERIES) SPACE(SU099*) ACCESS(RW)
  END
  END
