-- //*SSCOBSUP EXEC PROC=#REFSAUD,TS=SSCOBSUP                                   
SELECT '//*'||CHAR(STRIP(TSNAME),9)||'EXEC PROC=#REFSAUD,TS='||                 
       STRIP(TSNAME)                                                            
  FROM SYSIBM.SYSTABLES                                                         
 WHERE CREATOR = 'MARITIMA'                                                     
   AND TYPE = 'T'                                                               
   AND NAME IN (                                                                
'SSTIPRLAPTR',                                                                  
'SSCPVEQUIPE',                                                                  
'SSPCDEQUIPE',                                                                  
'SSDIVLHO',                                                                     
'SSGRAPTPPTR        ',                                                          
'SSGRPGLO           ',                                                          
'SSGRPMTVSAIINA     ',                                                          
'SSIDACD            ',                                                          
'SSMTVSAIINA        ',                                                          
'SSOBTMLH           ',                                                          
'SSRGMINA           ',                                                          
'SSTECUTL           ',                                                          
'SSTIPACO           ',                                                          
'SSTIPATD           ',                                                          
'SSTIPCAESOLGUI     ',                                                          
'SSTIPCNS           ',                                                          
'SSTIPDOE           ',                                                          
'SSTIPINA           ',                                                          
'SSTIPRLATPR        ',                                                          
'SSTIPSAI           ',                                                          
'SSTIPSAIGUI        ',                                                          
'SSTIPTAB           ',                                                          
'SSTIPTABPTR        ',                                                          
'SSTMPDOE           ',                                                          
'SSVIAACS           ',                                                          
'SSCNLDISGUI        ',                                                          
'SSCTLTIPGUI        ',                                                          
'SSCTLRSVGUI        ',                                                          
'SSCTLDISGUIPTR     ',                                                          
'SSGLOSAS           ',                                                          
'SSGIINSTCPMTISS    ',                                                          
'SSGIINSTCPMCID     ',                                                          
'SSGIINSTCPMOPM     ',                                                          
'SSUTLGUIPTR        ',                                                          
'SSGICOMP           ',                                                          
'SSGIPROG           ',                                                          
'SSLOTEGUIA         ',                                                          
'SSDADOCMUGUI       ',                                                          
'SSGUICONSULTAMDC   ',                                                          
'SSSERPRFSADT       ',                                                          
'SSHONMEDICOIND     ',                                                          
'SSRESUMOGUINA      ',                                                          
'SSPCDMDCREALIZADO  ',                                                          
'SSIDFEQUIPEMDC     ',                                                          
'SSOPMUTILIZADO     ',                                                          
'SSDESPESMDCADI     ',                                                          
'SSCARERRCPM        ',                                                          
'SSCAAMEMCPM        ',                                                          
'SSCAINHOCPM        ',                                                          
'SSCAPROCCPM        ',                                                          
'SSCPVEQU           ',                                                          
'SSEQUPCD           ',                                                          
'SSVENPRE           ',                                                          
'SSCACONS           ',                                                          
'SSCAHONO           ',                                                          
'SSDIVILHO          ')                                                          
ORDER BY TSNAME                                                                 
;                                                                       00005000
