GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  ADMDADOS ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AGUIAR   ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AUTO     ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AUTOCIR  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AUTOMAR  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AUTONEG  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AUTOSSA  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  AUTOWEB  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  BRAINP   ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  CA7ONL   ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  CLAUDIO  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  CORDSIS  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  DBAUSER  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  DETAIL   ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  FAEMISP  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  FEDUSER  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  JCARLOS  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  LUIS     ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  ONBASEP  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  ONBAUTP  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  PRIDE    ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  PROJETO  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  PROSISD  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  PROSISE  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  RESISE   ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  ROSCORP  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  ROSDBP   ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  SAUDE    ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  SCHED    ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  SEDA     ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  TMONDB2  ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  VIDA     ;          
COMMIT;                                                                         
GRANT INSERT,DELETE,SELECT,UPDATE ON TECINFOR.MOVSOLPCS TO  WAP001   ;          
COMMIT;                                                                         
