--
-- OBJETOS SEM BACKUP E JOBS BACKUP SEMANAIS
--
SELECT 'DB2A' AS SSID, JOBNAME, MAX(ICDATE) AS LAST_BKP
FROM SYSIBM.SYSCOPY
WHERE ICTYPE = 'F'
AND TIMESTAMP >=(CURRENT_TIMESTAMP - 30 DAYS)
AND DBNAME NOT IN ('DLCDB   ', 'CC390 '  )
AND JOBNAME NOT LIKE 'IBM1%'
AND SUBSTR (DBNAME,1,3)  NOT IN ('BMC', 'DSN', 'SYS', 'DB2', 'DBA')
GROUP BY JOBNAME ;
