SELECT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'PLAN' AS "TYPE",
       NAME, BCREATOR AS DEP_CREATOR, BNAME AS DEP_NAME,
       CASE BTYPE
            WHEN 'A' THEN 'ALIAS'
            WHEN 'E' THEN 'INSTEAD OF TRIGGER'
            WHEN 'F' THEN 'USER DEFINED FUNCTION'
            WHEN 'G' THEN 'GLOBAL TEMPORARY TABLE'
            WHEN 'I' THEN 'INDEX'
            WHEN 'M' THEN 'MQT'
            WHEN 'O' THEN 'STORED PROCEDURE'
            WHEN 'P' THEN 'PARTIONED TABLESPACE'
            WHEN 'Q' THEN 'SEQUENCE'
            WHEN 'R' THEN 'TABLE SPACE'
            WHEN 'S' THEN 'SYNONYM'
            WHEN 'T' THEN 'TABLE'
            WHEN 'V' THEN 'VIEW'
       END AS DEP_TYPE,
       BOUNDTS AS "LAST_BIND",
       VALID, OPERATIVE,
       LASTUSED
  FROM SYSIBM.SYSPLAN, SYSIBM.SYSPLANDEP
   WHERE
         NAME = DNAME
     AND LASTUSED  < CURRENT DATE - 12 MONTHS
UNION ALL
SELECT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'PKGE' AS "TYPE",
       C.NAME, A.BQUALIFIER, A.BNAME AS DEP_NAME,
       CASE A.BTYPE
            WHEN 'A' THEN 'ALIAS'
            WHEN 'B' THEN 'BUSINESS_TIME'
            WHEN 'C' THEN 'SYSTEM_TIME'
            WHEN 'E' THEN 'INSTEAD OF TRIGGER'
            WHEN 'F' THEN 'USER DEFINED FUNCTION'
            WHEN 'G' THEN 'GLOBAL TEMPORARY TABLE'
            WHEN 'I' THEN 'INDEX'
            WHEN 'M' THEN 'MQT'
            WHEN 'O' THEN 'STORED PROCEDURE'
            WHEN 'P' THEN 'PARTIONED TABLESPACE LARGE'
            WHEN 'Q' THEN 'SEQUENCE OBJECT'
            WHEN 'R' THEN 'TABLE SPACE'
            WHEN 'S' THEN 'SYNONYM'
            WHEN 'T' THEN 'TABLE'
            WHEN 'U' THEN 'DISTINCT TYPE'
            WHEN 'V' THEN 'VIEW'
            WHEN 'W' THEN 'SYSTEM_TIME PERIOD'
            WHEN 'Z' THEN 'BUSINESS_TIME PERIOD'
       END AS DEP_TYPE,
       C.BINDTIME  AS "LAST_BIND",
       C.VALID, C.OPERATIVE,
       C.LASTUSED
  FROM SYSIBM.SYSPACKAGE C, SYSIBM.SYSPACKDEP A,
       SYSIBM.SYSPACKLIST L
  WHERE C.LOCATION = A.DLOCATION
    AND C.COLLID = A.DCOLLID
    AND C.NAME   = A.DNAME
    AND LASTUSED  < CURRENT DATE - 12 MONTHS
    AND L.LOCATION = C.LOCATION
    AND L.COLLID   = C.COLLID
    AND L.NAME     = C.NAME
;
