--                                                                      00000100
-- GRANT INSERT ON OWNER.NAME TO GRANTEE;                               00000201
--                                                                      00000300
SELECT DISTINCT GRANTEE                                                 00000400
  FROM SYSIBM.SYSTABAUTH                                                00002000
 WHERE TCREATOR = 'DB2TEST'                                             00003000
   --AND SUBSTR(GRANTEE,1,2) <> 'ZZ'                                    00010000
   AND GRANTEETYPE = ' '                                                00010100
   AND (INSERTAUTH = 'Y' OR                                             00010200
        UPDATEAUTH = 'Y' OR                                             00010300
        DELETEAUTH = 'Y' )                                              00010400
   AND TTNAME IN ('BIL_ACT_INQUIRY',                                    00011000
                 'BIL_AMOUNTS',                                         00020000
                 'BIL_ACT_SUMMARY',                                     00030000
                 'BIL_ACCOUNT',                                         00040000
                 'BIL_CRG_AMOUNTS',                                     00050000
                 'BIL_CASH_DSP',                                        00060000
                 'BIL_CASH_ENTRY',                                      00070000
                 'BIL_CASH_RECEIPT',                                    00080000
                 'BIL_CRE_SCHEDULE',                                    00090000
                 'BIL_CASH_ENTRY_TOT',                                  00100000
                 'BIL_DATES',                                           00110000
                 'BIL_EFT_ACTIVITY',                                    00120000
                 'BIL_EFT_NOTICE',                                      00130000
                 'BIL_ERRORS',                                          00140000
                 'BIL_EFT_PND_TAPE',                                    00150000
                 'BIL_INV_DTL',                                         00160000
                 'BIL_INV_POL',                                         00170000
                 'BIL_NON_CPI_LET',                                     00180000
                 'BIL_POL_ACTIVITY',                                    00190000
                 'BIL_POLICY',                                          00200000
                 'BIL_POLICY_TRM',                                      00210000
                 'BIL_EFT_REJ_BCH',                                     00220000
                 'BIL_UN_ID_CASH',                                      00230000
                 'BIL_GD_EXCLUDE',                                      00240000
                 'BIL_ST_CANCTYPE',                                     00250000
                 'BIL_ACT_TCH_KEY',                                     00260000
                 'BIL_CRCRD_ARSP_DES',                                  00270000
                 'BIL_EFT_BANK_ED',                                     00280000
                 'BIL_BANK',                                            00290000
                 'BIL_BROADCAST_MSG',                                   00300000
                 'BIL_BILL_PLAN',                                       00310000
                 'BIL_CRCRD_DES',                                       00320000
                 'BIL_DES_REASON',                                      00330000
                 'BIL_EFT_BANK',                                        00340000
                 'BIL_EDITS',                                           00350000
                 'BIL_EFT_PLAN',                                        00360000
                 'BIL_ORG_SUPPORT',                                     00370000
                 'BIL_PAYABLE_ITEM',                                    00380000
                 'BIL_EFT_REJ_REA',                                     00390000
                 'BIL_SYSTEM_CFG',                                      00400000
                 'BIL_SUPPORT_PLAN',                                    00410000
                 'BIL_SYSTEM_RULES',                                    00420000
                 'BIL_RFI_CONVERT',                                     00430000
                 'BIL_AGENT',                                           00440000
                 'BIL_AGT_ACT_RLT',                                     00450000
                 'BIL_AGT_CASH_DSP',                                    00460000
                 'BIL_AGT_DATES',                                       00470000
                 'BIL_AGT_INQUIRY',                                     00480000
                 'BIL_AGT_TCH_KEY',                                     00490000
                 'BIL_AGT_CASH_RCT',                                    00500000
                 'BIL_AGT_SUMMARY',                                     00510000
                 'BIL_MCH_AGT_DTL',                                     00520000
                 'BIL_MCH_CMP_DTL',                                     00530000
                 'BIL_MATCH',                                           00540000
                 'BIL_AGT_STT_DTL',                                     00550000
                 'BIL_AGT_STT_TOT',                                     00560000
                 'BIL_INV_TTY_ACT',                                     00570000
                 'BIL_LH_SPT_PLAN',                                     00580000
                 'BIL_TTY_ACT_RLT',                                     00590000
                 'BIL_TTY_CASH_DSP',                                    00600000
                 'BIL_TTY_INQUIRY',                                     00610000
                 'BIL_TTY_TCH_KEY',                                     00620000
                 'BIL_THIRD_PARTY',                                     00630000
                 'BIL_TTY_CASH_RCT',                                    00640000
                 'BIL_TTY_DATES',                                       00650000
                 'BUS_ACY_COLLECTION',                                  00660000
                 'OUT_BAL_RPT_HDR',                                     00670000
                 'BUS_ACY_APP_PROD',                                    00680000
                 'BUS_ACY_LGG_CNV',                                     00690000
                 'BUS_ACY_MAIN_SUM',                                    00700000
                 'BUS_ACY_SUM_HST',                                     00710000
                 'BUS_ACY_SUM_VAL',                                     00720000
                 'BUS_ACY_TRS_ACTION',                                  00730000
                 'BUS_ACY_TRS_DESC',                                    00740000
                 'BUS_ACY_TRS_MSG',                                     00750000
                 'BUS_ACY_TRS_OBJECT',                                  00760000
                 'BUS_ACY_TRS_RULES',                                   00770000
                 'BUS_ACY_TRS_VRF',                                     00780000
                 'BUS_CMP_NBR_CNV',                                     00790000
                 'BUS_SUM_BAL_HST',                                     00800000
                 'OUT_BAL_DTL_TXT',                                     00810000
                 'OUT_BAL_HDR_TXT',                                     00820000
                 'OUT_BAL_RPT_DTL',                                     00830000
                 'BCM_BUS_ACTIVITY',                                    00840000
                 'CWS_BUS_ACTIVITY',                                    00850000
                 'DWS_BUS_ACTIVITY',                                    00860000
                 'ERR_BUS_ACTIVITY',                                    00870000
                 'FIN_BAL_RULES',                                       00880000
                 'FWS_BAL_BUS_CASE',                                    00890000
                 'FWS_IST_USER_SPT',                                    00900000
                 'MIS_BUS_ACTIVITY',                                    00910000
                 'RMS_BUS_ACTIVITY',                                    00920000
                 'UWS_BUS_ACTIVITY',                                    00930000
                 'ARCH_AGG_TBV',                                        00940000
                 'ARCH_DCG_FLD_CMT',                                    00950000
                 'ARCH_DOC_DATA',                                       00960000
                 'ARCH_DOC_SQL_INF',                                    00970000
                 'ARCH_DB_UPDATE',                                      00980000
                 'ARCH_DOC_DFLT',                                       00990000
                 'ARCH_DOC_TBL_INF',                                    01000000
                 'ARCH_DOC_MSC_INF',                                    01010000
                 'ARCH_DOC_FLD_INF',                                    01020000
                 'ARCH_DOC_GEN_INF',                                    01030000
                 'ARCH_DCG_TBLS',                                       01040000
                 'ARCH_DCG_FLDS',                                       01050000
                 'ARCH_DCG_LST_ASN',                                    01060000
                 'ARCH_DCG_TV_KEYS',                                    01070000
                 'ARCH_FLD_INUSE',                                      01080000
                 'ARCH_NODE',                                           01090000
                 'ARCH_SHR',                                            01100000
                 'ARCH_TBL_VIEW',                                       01110000
                 'ARCH_USER',                                           01120000
                 'ARCH_FDR_AGG',                                        01130000
                 'ARCH_HST_ERR_LOG',                                    01140000
                 'ARCH_HST_MSG_CD',                                     01150000
                 'ARCH_HST_MSG_TXT',                                    01160000
                 'BTH_ACY_QUE',                                         01170000
                 'BTH_DTA_QUE',                                         01180000
                 'DFR_ACY_QUE',                                         01190000
                 'DFR_DTA_QUE',                                         01200000
                 'DFR_IND_QUE',                                         01210000
                 'EDIT_TABLE',                                          01220000
                 'IMD_ACY_QUE',                                         01230000
                 'PRT_CD_TBL',                                          01240000
                 'PM_ERR',                                              01250000
                 'PRT_NM_TBL',                                          01260000
                 'PM_PLF',                                              01270000
                 'PROCESS_TAB',                                         01280000
                 'SAM_BASIC',                                           01290000
                 'SAM_POLICY',                                          01300000
                 'SAM_VEHICLE',                                         01310000
                 'WN_DATA',                                             01320000
                 'WN_DB_LOCK',                                          01330000
                 'WN_EDIT_FLD',                                         01340000
                 'WN_PM_PLF',                                           01350000
                 'CHF_STRUCTURE',                                       01360000
                 'CHF_UNIT',                                            01370000
                 'CHF_UNIT_RELATION',                                   01380000
                 'CHF_UNIT_TYPES',                                      01390000
                 'CMT_APL_PANEL',                                       01400000
                 'CMT_LINK',                                            01410000
                 'CMT_OBJECT',                                          01420000
                 'PEI_CND_RULE',                                        01430000
                 'PEI_PRT_INTF_MDU',                                    01440000
                 'PEI_PRT_CND',                                         01450000
                 'PEI_PRT_DTA',                                         01460000
                 'PEI_PRT_RTT',                                         01470000
                 'PEI_PRT_REQ',                                         01480000
                 'PSW_COLUMNS',                                         01490000
                 'PSW_DEFAULTS',                                        01500000
                 'PSW_EDITS',                                           01510000
                 'PSW_TBL_SEC',                                         01520000
                 'PSW_SYS_SPT',                                         01530000
                 'PSW_TABLES',                                          01540000
                 'WIP_ACY_ASN_RULE',                                    01550000
                 'WIP_ACY_CHECKLIST',                                   01560000
                 'WIP_CLASS_CTRL',                                      01570000
                 'WIP_HISTORY_EVENT',                                   01580000
                 'WIP_INITIATOR',                                       01590000
                 'WIP_ACTIVITY',                                        01600000
                 'WIP_DRY_CHECKLIST',                                   01610000
                 'WIP_DRY_HISTORY',                                     01620000
                 'WIP_DIARY',                                           01630000
                 'WIP_DRY_OBJECTS',                                     01640000
                 'WIP_GROUP_AUT',                                       01650000
                 'WIP_GROUPS',                                          01660000
                 'WIP_OBJ_LOCATE',                                      01670000
                 'WIP_PRIORITY',                                        01680000
                 'WIP_STATUS',                                          01690000
                 'WKM_BUS_CASE_DEF',                                    01700000
                 'WKM_BUS_CASE_LOG',                                    01710000
                 'WKM_BUS_CASE_STP',                                    01720000
                 'WKM_CASE_STEP_DEF',                                   01730000
                 'WKM_PRODUCT_TRANS',                                   01740000
                 'DWS_ACY_COLLECTION',                                  01750000
                 'DWS_CLIENT_RULES',                                    01760000
                 'DWS_CD_TXT',                                          01770000
                 'DWS_DSB_BCH_HST',                                     01780000
                 'DWS_DSB_CLIENT',                                      01790000
                 'DWS_DISBURSEMENT',                                    01800000
                 'DWS_ERR_ACTIVITY',                                    01810000
                 'DWS_IVT_CONTROL',                                     01820000
                 'DWS_IVT_DETAIL',                                      01830000
                 'DWS_LOCATION_RULES',                                  01840000
                 'DWS_OUTPUT_FMT',                                      01850000
                 'DWS_RULE',                                            01860000
                 'DWS_STATUS_HST',                                      01870000
                 'DWS_TXT',                                             01880000
                 'ERROR_STORAGE',                                       01890000
                 'POLICY_CLIENT',                                       01900000
                 'POLICY_TAB',                                          01910000
                 'DWELLING_TAB',                                        01920000
                 'DWELLING_CLIENT',                                     01930000
                 'LEGAL_DAYS_NOTICE',                                   01940000
                 'CANC_TRIGGER',                                        01950000
                 'PINT_LATE_FEE',                                       01960000
                 'PINT_RESTART',                                        01970000
                 'PINT_CANC_FORM',                                      01980000
                 'PINT_PRODUCER_PIR',                                   01990000
                 'PINT_GL_SUMMARY',                                     02000000
                 'PINT_GL_DETAIL',                                      02010000
                 'PINT_GL_PREM_ISS',                                    02020000
                 'PINT_COMMISSION',                                     02030000
                 'PINT_GS_DETAIL',                                      02040000
                 'PINT_CHKPT_FRQ',                                      02050000
                 'PINT_ERROR_MESSAGE',                                  02060000
                 'PINT_POSTNET_BCODE',                                  02070000
                 'PINT_PREM_RCYL_EXT')                                  02080000
; --UNION ALL                                                           02081000
SELECT                                                                  02082000
' GRANT INSERT ON '||STRIP(TCREATOR)||'.'||STRIP(TTNAME)||              02083001
' TO '||STRIP(GRANTEE)||';'                                             02084001
  FROM SYSIBM.SYSTABAUTH                                                02085000
 WHERE TCREATOR = 'DB2TEST'                                             02086000
   AND GRANTEETYPE = ' '                                                02086100
   --AND SUBSTR(GRANTEE,1,2) <> 'ZZ'                                    02087000
   AND INSERTAUTH = 'Y'                                                 02088000
   AND TTNAME IN ('BIL_ACT_INQUIRY',                                    02089000
                 'BIL_AMOUNTS',                                         02089100
                 'BIL_ACT_SUMMARY',                                     02089200
                 'BIL_ACCOUNT',                                         02089300
                 'BIL_CRG_AMOUNTS',                                     02089400
                 'BIL_CASH_DSP',                                        02089500
                 'BIL_CASH_ENTRY',                                      02089600
                 'BIL_CASH_RECEIPT',                                    02089700
                 'BIL_CRE_SCHEDULE',                                    02089800
                 'BIL_CASH_ENTRY_TOT',                                  02089900
                 'BIL_DATES',                                           02090000
                 'BIL_EFT_ACTIVITY',                                    02090100
                 'BIL_EFT_NOTICE',                                      02090200
                 'BIL_ERRORS',                                          02090300
                 'BIL_EFT_PND_TAPE',                                    02090400
                 'BIL_INV_DTL',                                         02090500
                 'BIL_INV_POL',                                         02090600
                 'BIL_NON_CPI_LET',                                     02090700
                 'BIL_POL_ACTIVITY',                                    02090800
                 'BIL_POLICY',                                          02090900
                 'BIL_POLICY_TRM',                                      02091000
                 'BIL_EFT_REJ_BCH',                                     02091100
                 'BIL_UN_ID_CASH',                                      02091200
                 'BIL_GD_EXCLUDE',                                      02091300
                 'BIL_ST_CANCTYPE',                                     02091400
                 'BIL_ACT_TCH_KEY',                                     02091500
                 'BIL_CRCRD_ARSP_DES',                                  02091600
                 'BIL_EFT_BANK_ED',                                     02091700
                 'BIL_BANK',                                            02091800
                 'BIL_BROADCAST_MSG',                                   02091900
                 'BIL_BILL_PLAN',                                       02092000
                 'BIL_CRCRD_DES',                                       02092100
                 'BIL_DES_REASON',                                      02092200
                 'BIL_EFT_BANK',                                        02092300
                 'BIL_EDITS',                                           02092400
                 'BIL_EFT_PLAN',                                        02092500
                 'BIL_ORG_SUPPORT',                                     02092600
                 'BIL_PAYABLE_ITEM',                                    02092700
                 'BIL_EFT_REJ_REA',                                     02092800
                 'BIL_SYSTEM_CFG',                                      02092900
                 'BIL_SUPPORT_PLAN',                                    02093000
                 'BIL_SYSTEM_RULES',                                    02093100
                 'BIL_RFI_CONVERT',                                     02093200
                 'BIL_AGENT',                                           02093300
                 'BIL_AGT_ACT_RLT',                                     02093400
                 'BIL_AGT_CASH_DSP',                                    02093500
                 'BIL_AGT_DATES',                                       02093600
                 'BIL_AGT_INQUIRY',                                     02093700
                 'BIL_AGT_TCH_KEY',                                     02093800
                 'BIL_AGT_CASH_RCT',                                    02093900
                 'BIL_AGT_SUMMARY',                                     02094000
                 'BIL_MCH_AGT_DTL',                                     02094100
                 'BIL_MCH_CMP_DTL',                                     02094200
                 'BIL_MATCH',                                           02094300
                 'BIL_AGT_STT_DTL',                                     02094400
                 'BIL_AGT_STT_TOT',                                     02094500
                 'BIL_INV_TTY_ACT',                                     02094600
                 'BIL_LH_SPT_PLAN',                                     02094700
                 'BIL_TTY_ACT_RLT',                                     02094800
                 'BIL_TTY_CASH_DSP',                                    02094900
                 'BIL_TTY_INQUIRY',                                     02095000
                 'BIL_TTY_TCH_KEY',                                     02095100
                 'BIL_THIRD_PARTY',                                     02095200
                 'BIL_TTY_CASH_RCT',                                    02095300
                 'BIL_TTY_DATES',                                       02095400
                 'BUS_ACY_COLLECTION',                                  02095500
                 'OUT_BAL_RPT_HDR',                                     02095600
                 'BUS_ACY_APP_PROD',                                    02095700
                 'BUS_ACY_LGG_CNV',                                     02095800
                 'BUS_ACY_MAIN_SUM',                                    02095900
                 'BUS_ACY_SUM_HST',                                     02096000
                 'BUS_ACY_SUM_VAL',                                     02096100
                 'BUS_ACY_TRS_ACTION',                                  02096200
                 'BUS_ACY_TRS_DESC',                                    02096300
                 'BUS_ACY_TRS_MSG',                                     02096400
                 'BUS_ACY_TRS_OBJECT',                                  02096500
                 'BUS_ACY_TRS_RULES',                                   02096600
                 'BUS_ACY_TRS_VRF',                                     02096700
                 'BUS_CMP_NBR_CNV',                                     02096800
                 'BUS_SUM_BAL_HST',                                     02096900
                 'OUT_BAL_DTL_TXT',                                     02097000
                 'OUT_BAL_HDR_TXT',                                     02097100
                 'OUT_BAL_RPT_DTL',                                     02097200
                 'BCM_BUS_ACTIVITY',                                    02097300
                 'CWS_BUS_ACTIVITY',                                    02097400
                 'DWS_BUS_ACTIVITY',                                    02097500
                 'ERR_BUS_ACTIVITY',                                    02097600
                 'FIN_BAL_RULES',                                       02097700
                 'FWS_BAL_BUS_CASE',                                    02097800
                 'FWS_IST_USER_SPT',                                    02097900
                 'MIS_BUS_ACTIVITY',                                    02098000
                 'RMS_BUS_ACTIVITY',                                    02098100
                 'UWS_BUS_ACTIVITY',                                    02098200
                 'ARCH_AGG_TBV',                                        02098300
                 'ARCH_DCG_FLD_CMT',                                    02098400
                 'ARCH_DOC_DATA',                                       02098500
                 'ARCH_DOC_SQL_INF',                                    02098600
                 'ARCH_DB_UPDATE',                                      02098700
                 'ARCH_DOC_DFLT',                                       02098800
                 'ARCH_DOC_TBL_INF',                                    02098900
                 'ARCH_DOC_MSC_INF',                                    02099000
                 'ARCH_DOC_FLD_INF',                                    02099100
                 'ARCH_DOC_GEN_INF',                                    02099200
                 'ARCH_DCG_TBLS',                                       02099300
                 'ARCH_DCG_FLDS',                                       02099400
                 'ARCH_DCG_LST_ASN',                                    02099500
                 'ARCH_DCG_TV_KEYS',                                    02099600
                 'ARCH_FLD_INUSE',                                      02099700
                 'ARCH_NODE',                                           02099800
                 'ARCH_SHR',                                            02099900
                 'ARCH_TBL_VIEW',                                       02100000
                 'ARCH_USER',                                           02100100
                 'ARCH_FDR_AGG',                                        02100200
                 'ARCH_HST_ERR_LOG',                                    02100300
                 'ARCH_HST_MSG_CD',                                     02100400
                 'ARCH_HST_MSG_TXT',                                    02100500
                 'BTH_ACY_QUE',                                         02100600
                 'BTH_DTA_QUE',                                         02100700
                 'DFR_ACY_QUE',                                         02100800
                 'DFR_DTA_QUE',                                         02100900
                 'DFR_IND_QUE',                                         02101000
                 'EDIT_TABLE',                                          02101100
                 'IMD_ACY_QUE',                                         02101200
                 'PRT_CD_TBL',                                          02101300
                 'PM_ERR',                                              02101400
                 'PRT_NM_TBL',                                          02101500
                 'PM_PLF',                                              02101600
                 'PROCESS_TAB',                                         02101700
                 'SAM_BASIC',                                           02101800
                 'SAM_POLICY',                                          02101900
                 'SAM_VEHICLE',                                         02102000
                 'WN_DATA',                                             02102100
                 'WN_DB_LOCK',                                          02102200
                 'WN_EDIT_FLD',                                         02102300
                 'WN_PM_PLF',                                           02102400
                 'CHF_STRUCTURE',                                       02102500
                 'CHF_UNIT',                                            02102600
                 'CHF_UNIT_RELATION',                                   02102700
                 'CHF_UNIT_TYPES',                                      02102800
                 'CMT_APL_PANEL',                                       02102900
                 'CMT_LINK',                                            02103000
                 'CMT_OBJECT',                                          02103100
                 'PEI_CND_RULE',                                        02103200
                 'PEI_PRT_INTF_MDU',                                    02103300
                 'PEI_PRT_CND',                                         02103400
                 'PEI_PRT_DTA',                                         02103500
                 'PEI_PRT_RTT',                                         02103600
                 'PEI_PRT_REQ',                                         02103700
                 'PSW_COLUMNS',                                         02103800
                 'PSW_DEFAULTS',                                        02103900
                 'PSW_EDITS',                                           02104000
                 'PSW_TBL_SEC',                                         02104100
                 'PSW_SYS_SPT',                                         02104200
                 'PSW_TABLES',                                          02104300
                 'WIP_ACY_ASN_RULE',                                    02104400
                 'WIP_ACY_CHECKLIST',                                   02104500
                 'WIP_CLASS_CTRL',                                      02104600
                 'WIP_HISTORY_EVENT',                                   02104700
                 'WIP_INITIATOR',                                       02104800
                 'WIP_ACTIVITY',                                        02104900
                 'WIP_DRY_CHECKLIST',                                   02105000
                 'WIP_DRY_HISTORY',                                     02105100
                 'WIP_DIARY',                                           02105200
                 'WIP_DRY_OBJECTS',                                     02105300
                 'WIP_GROUP_AUT',                                       02105400
                 'WIP_GROUPS',                                          02105500
                 'WIP_OBJ_LOCATE',                                      02105600
                 'WIP_PRIORITY',                                        02105700
                 'WIP_STATUS',                                          02105800
                 'WKM_BUS_CASE_DEF',                                    02105900
                 'WKM_BUS_CASE_LOG',                                    02106000
                 'WKM_BUS_CASE_STP',                                    02106100
                 'WKM_CASE_STEP_DEF',                                   02106200
                 'WKM_PRODUCT_TRANS',                                   02106300
                 'DWS_ACY_COLLECTION',                                  02106400
                 'DWS_CLIENT_RULES',                                    02106500
                 'DWS_CD_TXT',                                          02106600
                 'DWS_DSB_BCH_HST',                                     02106700
                 'DWS_DSB_CLIENT',                                      02106800
                 'DWS_DISBURSEMENT',                                    02106900
                 'DWS_ERR_ACTIVITY',                                    02107000
                 'DWS_IVT_CONTROL',                                     02107100
                 'DWS_IVT_DETAIL',                                      02107200
                 'DWS_LOCATION_RULES',                                  02107300
                 'DWS_OUTPUT_FMT',                                      02107400
                 'DWS_RULE',                                            02107500
                 'DWS_STATUS_HST',                                      02107600
                 'DWS_TXT',                                             02107700
                 'ERROR_STORAGE',                                       02107800
                 'POLICY_CLIENT',                                       02107900
                 'POLICY_TAB',                                          02108000
                 'DWELLING_TAB',                                        02108100
                 'DWELLING_CLIENT',                                     02108200
                 'LEGAL_DAYS_NOTICE',                                   02108300
                 'CANC_TRIGGER',                                        02108400
                 'PINT_LATE_FEE',                                       02108500
                 'PINT_RESTART',                                        02108600
                 'PINT_CANC_FORM',                                      02108700
                 'PINT_PRODUCER_PIR',                                   02108800
                 'PINT_GL_SUMMARY',                                     02108900
                 'PINT_GL_DETAIL',                                      02109000
                 'PINT_GL_PREM_ISS',                                    02109100
                 'PINT_COMMISSION',                                     02109200
                 'PINT_GS_DETAIL',                                      02109300
                 'PINT_CHKPT_FRQ',                                      02109400
                 'PINT_ERROR_MESSAGE',                                  02109500
                 'PINT_POSTNET_BCODE',                                  02109600
                 'PINT_PREM_RCYL_EXT')                                  02109700
; --UNION ALL                                                           02109800
SELECT                                                                  02109900
' GRANT UPDATE ON '||STRIP(TCREATOR)||'.'||STRIP(TTNAME)||              02110001
' TO '||STRIP(GRANTEE)||';'                                             02111001
  FROM SYSIBM.SYSTABAUTH                                                02120000
 WHERE TCREATOR = 'DB2TEST'                                             02130000
   AND GRANTEETYPE = ' '                                                02131000
   --AND SUBSTR(GRANTEE,1,2) <> 'ZZ'                                    02140000
   AND UPDATEAUTH = 'Y'                                                 02150000
   AND TTNAME IN ('BIL_ACT_INQUIRY',                                    02160000
                 'BIL_AMOUNTS',                                         02170000
                 'BIL_ACT_SUMMARY',                                     02180000
                 'BIL_ACCOUNT',                                         02190000
                 'BIL_CRG_AMOUNTS',                                     02200000
                 'BIL_CASH_DSP',                                        02210000
                 'BIL_CASH_ENTRY',                                      02220000
                 'BIL_CASH_RECEIPT',                                    02230000
                 'BIL_CRE_SCHEDULE',                                    02240000
                 'BIL_CASH_ENTRY_TOT',                                  02250000
                 'BIL_DATES',                                           02260000
                 'BIL_EFT_ACTIVITY',                                    02270000
                 'BIL_EFT_NOTICE',                                      02280000
                 'BIL_ERRORS',                                          02290000
                 'BIL_EFT_PND_TAPE',                                    02300000
                 'BIL_INV_DTL',                                         02310000
                 'BIL_INV_POL',                                         02320000
                 'BIL_NON_CPI_LET',                                     02330000
                 'BIL_POL_ACTIVITY',                                    02340000
                 'BIL_POLICY',                                          02350000
                 'BIL_POLICY_TRM',                                      02360000
                 'BIL_EFT_REJ_BCH',                                     02370000
                 'BIL_UN_ID_CASH',                                      02380000
                 'BIL_GD_EXCLUDE',                                      02390000
                 'BIL_ST_CANCTYPE',                                     02400000
                 'BIL_ACT_TCH_KEY',                                     02410000
                 'BIL_CRCRD_ARSP_DES',                                  02420000
                 'BIL_EFT_BANK_ED',                                     02430000
                 'BIL_BANK',                                            02440000
                 'BIL_BROADCAST_MSG',                                   02450000
                 'BIL_BILL_PLAN',                                       02460000
                 'BIL_CRCRD_DES',                                       02470000
                 'BIL_DES_REASON',                                      02480000
                 'BIL_EFT_BANK',                                        02490000
                 'BIL_EDITS',                                           02500000
                 'BIL_EFT_PLAN',                                        02510000
                 'BIL_ORG_SUPPORT',                                     02520000
                 'BIL_PAYABLE_ITEM',                                    02530000
                 'BIL_EFT_REJ_REA',                                     02540000
                 'BIL_SYSTEM_CFG',                                      02550000
                 'BIL_SUPPORT_PLAN',                                    02560000
                 'BIL_SYSTEM_RULES',                                    02570000
                 'BIL_RFI_CONVERT',                                     02580000
                 'BIL_AGENT',                                           02590000
                 'BIL_AGT_ACT_RLT',                                     02600000
                 'BIL_AGT_CASH_DSP',                                    02610000
                 'BIL_AGT_DATES',                                       02620000
                 'BIL_AGT_INQUIRY',                                     02630000
                 'BIL_AGT_TCH_KEY',                                     02640000
                 'BIL_AGT_CASH_RCT',                                    02650000
                 'BIL_AGT_SUMMARY',                                     02660000
                 'BIL_MCH_AGT_DTL',                                     02670000
                 'BIL_MCH_CMP_DTL',                                     02680000
                 'BIL_MATCH',                                           02690000
                 'BIL_AGT_STT_DTL',                                     02700000
                 'BIL_AGT_STT_TOT',                                     02710000
                 'BIL_INV_TTY_ACT',                                     02720000
                 'BIL_LH_SPT_PLAN',                                     02730000
                 'BIL_TTY_ACT_RLT',                                     02740000
                 'BIL_TTY_CASH_DSP',                                    02750000
                 'BIL_TTY_INQUIRY',                                     02760000
                 'BIL_TTY_TCH_KEY',                                     02770000
                 'BIL_THIRD_PARTY',                                     02780000
                 'BIL_TTY_CASH_RCT',                                    02790000
                 'BIL_TTY_DATES',                                       02800000
                 'BUS_ACY_COLLECTION',                                  02810000
                 'OUT_BAL_RPT_HDR',                                     02820000
                 'BUS_ACY_APP_PROD',                                    02830000
                 'BUS_ACY_LGG_CNV',                                     02840000
                 'BUS_ACY_MAIN_SUM',                                    02850000
                 'BUS_ACY_SUM_HST',                                     02860000
                 'BUS_ACY_SUM_VAL',                                     02870000
                 'BUS_ACY_TRS_ACTION',                                  02880000
                 'BUS_ACY_TRS_DESC',                                    02890000
                 'BUS_ACY_TRS_MSG',                                     02900000
                 'BUS_ACY_TRS_OBJECT',                                  02910000
                 'BUS_ACY_TRS_RULES',                                   02920000
                 'BUS_ACY_TRS_VRF',                                     02930000
                 'BUS_CMP_NBR_CNV',                                     02940000
                 'BUS_SUM_BAL_HST',                                     02950000
                 'OUT_BAL_DTL_TXT',                                     02960000
                 'OUT_BAL_HDR_TXT',                                     02970000
                 'OUT_BAL_RPT_DTL',                                     02980000
                 'BCM_BUS_ACTIVITY',                                    02990000
                 'CWS_BUS_ACTIVITY',                                    03000000
                 'DWS_BUS_ACTIVITY',                                    03010000
                 'ERR_BUS_ACTIVITY',                                    03020000
                 'FIN_BAL_RULES',                                       03030000
                 'FWS_BAL_BUS_CASE',                                    03040000
                 'FWS_IST_USER_SPT',                                    03050000
                 'MIS_BUS_ACTIVITY',                                    03060000
                 'RMS_BUS_ACTIVITY',                                    03070000
                 'UWS_BUS_ACTIVITY',                                    03080000
                 'ARCH_AGG_TBV',                                        03090000
                 'ARCH_DCG_FLD_CMT',                                    03100000
                 'ARCH_DOC_DATA',                                       03110000
                 'ARCH_DOC_SQL_INF',                                    03120000
                 'ARCH_DB_UPDATE',                                      03130000
                 'ARCH_DOC_DFLT',                                       03140000
                 'ARCH_DOC_TBL_INF',                                    03150000
                 'ARCH_DOC_MSC_INF',                                    03160000
                 'ARCH_DOC_FLD_INF',                                    03170000
                 'ARCH_DOC_GEN_INF',                                    03180000
                 'ARCH_DCG_TBLS',                                       03190000
                 'ARCH_DCG_FLDS',                                       03200000
                 'ARCH_DCG_LST_ASN',                                    03210000
                 'ARCH_DCG_TV_KEYS',                                    03220000
                 'ARCH_FLD_INUSE',                                      03230000
                 'ARCH_NODE',                                           03240000
                 'ARCH_SHR',                                            03250000
                 'ARCH_TBL_VIEW',                                       03260000
                 'ARCH_USER',                                           03270000
                 'ARCH_FDR_AGG',                                        03280000
                 'ARCH_HST_ERR_LOG',                                    03290000
                 'ARCH_HST_MSG_CD',                                     03300000
                 'ARCH_HST_MSG_TXT',                                    03310000
                 'BTH_ACY_QUE',                                         03320000
                 'BTH_DTA_QUE',                                         03330000
                 'DFR_ACY_QUE',                                         03340000
                 'DFR_DTA_QUE',                                         03350000
                 'DFR_IND_QUE',                                         03360000
                 'EDIT_TABLE',                                          03370000
                 'IMD_ACY_QUE',                                         03380000
                 'PRT_CD_TBL',                                          03390000
                 'PM_ERR',                                              03400000
                 'PRT_NM_TBL',                                          03410000
                 'PM_PLF',                                              03420000
                 'PROCESS_TAB',                                         03430000
                 'SAM_BASIC',                                           03440000
                 'SAM_POLICY',                                          03450000
                 'SAM_VEHICLE',                                         03460000
                 'WN_DATA',                                             03470000
                 'WN_DB_LOCK',                                          03480000
                 'WN_EDIT_FLD',                                         03490000
                 'WN_PM_PLF',                                           03500000
                 'CHF_STRUCTURE',                                       03510000
                 'CHF_UNIT',                                            03520000
                 'CHF_UNIT_RELATION',                                   03530000
                 'CHF_UNIT_TYPES',                                      03540000
                 'CMT_APL_PANEL',                                       03550000
                 'CMT_LINK',                                            03560000
                 'CMT_OBJECT',                                          03570000
                 'PEI_CND_RULE',                                        03580000
                 'PEI_PRT_INTF_MDU',                                    03590000
                 'PEI_PRT_CND',                                         03600000
                 'PEI_PRT_DTA',                                         03610000
                 'PEI_PRT_RTT',                                         03620000
                 'PEI_PRT_REQ',                                         03630000
                 'PSW_COLUMNS',                                         03640000
                 'PSW_DEFAULTS',                                        03650000
                 'PSW_EDITS',                                           03660000
                 'PSW_TBL_SEC',                                         03670000
                 'PSW_SYS_SPT',                                         03680000
                 'PSW_TABLES',                                          03690000
                 'WIP_ACY_ASN_RULE',                                    03700000
                 'WIP_ACY_CHECKLIST',                                   03710000
                 'WIP_CLASS_CTRL',                                      03720000
                 'WIP_HISTORY_EVENT',                                   03730000
                 'WIP_INITIATOR',                                       03740000
                 'WIP_ACTIVITY',                                        03750000
                 'WIP_DRY_CHECKLIST',                                   03760000
                 'WIP_DRY_HISTORY',                                     03770000
                 'WIP_DIARY',                                           03780000
                 'WIP_DRY_OBJECTS',                                     03790000
                 'WIP_GROUP_AUT',                                       03800000
                 'WIP_GROUPS',                                          03810000
                 'WIP_OBJ_LOCATE',                                      03820000
                 'WIP_PRIORITY',                                        03830000
                 'WIP_STATUS',                                          03840000
                 'WKM_BUS_CASE_DEF',                                    03850000
                 'WKM_BUS_CASE_LOG',                                    03860000
                 'WKM_BUS_CASE_STP',                                    03870000
                 'WKM_CASE_STEP_DEF',                                   03880000
                 'WKM_PRODUCT_TRANS',                                   03890000
                 'DWS_ACY_COLLECTION',                                  03900000
                 'DWS_CLIENT_RULES',                                    03910000
                 'DWS_CD_TXT',                                          03920000
                 'DWS_DSB_BCH_HST',                                     03930000
                 'DWS_DSB_CLIENT',                                      03940000
                 'DWS_DISBURSEMENT',                                    03950000
                 'DWS_ERR_ACTIVITY',                                    03960000
                 'DWS_IVT_CONTROL',                                     03970000
                 'DWS_IVT_DETAIL',                                      03980000
                 'DWS_LOCATION_RULES',                                  03990000
                 'DWS_OUTPUT_FMT',                                      04000000
                 'DWS_RULE',                                            04010000
                 'DWS_STATUS_HST',                                      04020000
                 'DWS_TXT',                                             04030000
                 'ERROR_STORAGE',                                       04040000
                 'POLICY_CLIENT',                                       04050000
                 'POLICY_TAB',                                          04060000
                 'DWELLING_TAB',                                        04070000
                 'DWELLING_CLIENT',                                     04080000
                 'LEGAL_DAYS_NOTICE',                                   04090000
                 'CANC_TRIGGER',                                        04100000
                 'PINT_LATE_FEE',                                       04110000
                 'PINT_RESTART',                                        04120000
                 'PINT_CANC_FORM',                                      04130000
                 'PINT_PRODUCER_PIR',                                   04140000
                 'PINT_GL_SUMMARY',                                     04150000
                 'PINT_GL_DETAIL',                                      04160000
                 'PINT_GL_PREM_ISS',                                    04170000
                 'PINT_COMMISSION',                                     04180000
                 'PINT_GS_DETAIL',                                      04190000
                 'PINT_CHKPT_FRQ',                                      04200000
                 'PINT_ERROR_MESSAGE',                                  04210000
                 'PINT_POSTNET_BCODE',                                  04220000
                 'PINT_PREM_RCYL_EXT')                                  04230000
; --UNION ALL                                                           04240000
SELECT                                                                  04250000
' GRANT DELETE ON '||STRIP(TCREATOR)||'.'||STRIP(TTNAME)||              04260001
' TO '||STRIP(GRANTEE)||';'                                             04270001
  FROM SYSIBM.SYSTABAUTH                                                04280000
 WHERE TCREATOR = 'DB2TEST'                                             04290000
   AND GRANTEETYPE = ' '                                                04291000
   --AND SUBSTR(GRANTEE,1,2) <> 'ZZ'                                    04300000
   AND DELETEAUTH = 'Y'                                                 04310000
   AND TTNAME IN ('BIL_ACT_INQUIRY',                                    04320000
                 'BIL_AMOUNTS',                                         04330000
                 'BIL_ACT_SUMMARY',                                     04340000
                 'BIL_ACCOUNT',                                         04350000
                 'BIL_CRG_AMOUNTS',                                     04360000
                 'BIL_CASH_DSP',                                        04370000
                 'BIL_CASH_ENTRY',                                      04380000
                 'BIL_CASH_RECEIPT',                                    04390000
                 'BIL_CRE_SCHEDULE',                                    04400000
                 'BIL_CASH_ENTRY_TOT',                                  04410000
                 'BIL_DATES',                                           04420000
                 'BIL_EFT_ACTIVITY',                                    04430000
                 'BIL_EFT_NOTICE',                                      04440000
                 'BIL_ERRORS',                                          04450000
                 'BIL_EFT_PND_TAPE',                                    04460000
                 'BIL_INV_DTL',                                         04470000
                 'BIL_INV_POL',                                         04480000
                 'BIL_NON_CPI_LET',                                     04490000
                 'BIL_POL_ACTIVITY',                                    04500000
                 'BIL_POLICY',                                          04510000
                 'BIL_POLICY_TRM',                                      04520000
                 'BIL_EFT_REJ_BCH',                                     04530000
                 'BIL_UN_ID_CASH',                                      04540000
                 'BIL_GD_EXCLUDE',                                      04550000
                 'BIL_ST_CANCTYPE',                                     04560000
                 'BIL_ACT_TCH_KEY',                                     04570000
                 'BIL_CRCRD_ARSP_DES',                                  04580000
                 'BIL_EFT_BANK_ED',                                     04590000
                 'BIL_BANK',                                            04600000
                 'BIL_BROADCAST_MSG',                                   04610000
                 'BIL_BILL_PLAN',                                       04620000
                 'BIL_CRCRD_DES',                                       04630000
                 'BIL_DES_REASON',                                      04640000
                 'BIL_EFT_BANK',                                        04650000
                 'BIL_EDITS',                                           04660000
                 'BIL_EFT_PLAN',                                        04670000
                 'BIL_ORG_SUPPORT',                                     04680000
                 'BIL_PAYABLE_ITEM',                                    04690000
                 'BIL_EFT_REJ_REA',                                     04700000
                 'BIL_SYSTEM_CFG',                                      04710000
                 'BIL_SUPPORT_PLAN',                                    04720000
                 'BIL_SYSTEM_RULES',                                    04730000
                 'BIL_RFI_CONVERT',                                     04740000
                 'BIL_AGENT',                                           04750000
                 'BIL_AGT_ACT_RLT',                                     04760000
                 'BIL_AGT_CASH_DSP',                                    04770000
                 'BIL_AGT_DATES',                                       04780000
                 'BIL_AGT_INQUIRY',                                     04790000
                 'BIL_AGT_TCH_KEY',                                     04800000
                 'BIL_AGT_CASH_RCT',                                    04810000
                 'BIL_AGT_SUMMARY',                                     04820000
                 'BIL_MCH_AGT_DTL',                                     04830000
                 'BIL_MCH_CMP_DTL',                                     04840000
                 'BIL_MATCH',                                           04850000
                 'BIL_AGT_STT_DTL',                                     04860000
                 'BIL_AGT_STT_TOT',                                     04870000
                 'BIL_INV_TTY_ACT',                                     04880000
                 'BIL_LH_SPT_PLAN',                                     04890000
                 'BIL_TTY_ACT_RLT',                                     04900000
                 'BIL_TTY_CASH_DSP',                                    04910000
                 'BIL_TTY_INQUIRY',                                     04920000
                 'BIL_TTY_TCH_KEY',                                     04930000
                 'BIL_THIRD_PARTY',                                     04940000
                 'BIL_TTY_CASH_RCT',                                    04950000
                 'BIL_TTY_DATES',                                       04960000
                 'BUS_ACY_COLLECTION',                                  04970000
                 'OUT_BAL_RPT_HDR',                                     04980000
                 'BUS_ACY_APP_PROD',                                    04990000
                 'BUS_ACY_LGG_CNV',                                     05000000
                 'BUS_ACY_MAIN_SUM',                                    05010000
                 'BUS_ACY_SUM_HST',                                     05020000
                 'BUS_ACY_SUM_VAL',                                     05030000
                 'BUS_ACY_TRS_ACTION',                                  05040000
                 'BUS_ACY_TRS_DESC',                                    05050000
                 'BUS_ACY_TRS_MSG',                                     05060000
                 'BUS_ACY_TRS_OBJECT',                                  05070000
                 'BUS_ACY_TRS_RULES',                                   05080000
                 'BUS_ACY_TRS_VRF',                                     05090000
                 'BUS_CMP_NBR_CNV',                                     05100000
                 'BUS_SUM_BAL_HST',                                     05110000
                 'OUT_BAL_DTL_TXT',                                     05120000
                 'OUT_BAL_HDR_TXT',                                     05130000
                 'OUT_BAL_RPT_DTL',                                     05140000
                 'BCM_BUS_ACTIVITY',                                    05150000
                 'CWS_BUS_ACTIVITY',                                    05160000
                 'DWS_BUS_ACTIVITY',                                    05170000
                 'ERR_BUS_ACTIVITY',                                    05180000
                 'FIN_BAL_RULES',                                       05190000
                 'FWS_BAL_BUS_CASE',                                    05200000
                 'FWS_IST_USER_SPT',                                    05210000
                 'MIS_BUS_ACTIVITY',                                    05220000
                 'RMS_BUS_ACTIVITY',                                    05230000
                 'UWS_BUS_ACTIVITY',                                    05240000
                 'ARCH_AGG_TBV',                                        05250000
                 'ARCH_DCG_FLD_CMT',                                    05260000
                 'ARCH_DOC_DATA',                                       05270000
                 'ARCH_DOC_SQL_INF',                                    05280000
                 'ARCH_DB_UPDATE',                                      05290000
                 'ARCH_DOC_DFLT',                                       05300000
                 'ARCH_DOC_TBL_INF',                                    05310000
                 'ARCH_DOC_MSC_INF',                                    05320000
                 'ARCH_DOC_FLD_INF',                                    05330000
                 'ARCH_DOC_GEN_INF',                                    05340000
                 'ARCH_DCG_TBLS',                                       05350000
                 'ARCH_DCG_FLDS',                                       05360000
                 'ARCH_DCG_LST_ASN',                                    05370000
                 'ARCH_DCG_TV_KEYS',                                    05380000
                 'ARCH_FLD_INUSE',                                      05390000
                 'ARCH_NODE',                                           05400000
                 'ARCH_SHR',                                            05410000
                 'ARCH_TBL_VIEW',                                       05420000
                 'ARCH_USER',                                           05430000
                 'ARCH_FDR_AGG',                                        05440000
                 'ARCH_HST_ERR_LOG',                                    05450000
                 'ARCH_HST_MSG_CD',                                     05460000
                 'ARCH_HST_MSG_TXT',                                    05470000
                 'BTH_ACY_QUE',                                         05480000
                 'BTH_DTA_QUE',                                         05490000
                 'DFR_ACY_QUE',                                         05500000
                 'DFR_DTA_QUE',                                         05510000
                 'DFR_IND_QUE',                                         05520000
                 'EDIT_TABLE',                                          05530000
                 'IMD_ACY_QUE',                                         05540000
                 'PRT_CD_TBL',                                          05550000
                 'PM_ERR',                                              05560000
                 'PRT_NM_TBL',                                          05570000
                 'PM_PLF',                                              05580000
                 'PROCESS_TAB',                                         05590000
                 'SAM_BASIC',                                           05600000
                 'SAM_POLICY',                                          05610000
                 'SAM_VEHICLE',                                         05620000
                 'WN_DATA',                                             05630000
                 'WN_DB_LOCK',                                          05640000
                 'WN_EDIT_FLD',                                         05650000
                 'WN_PM_PLF',                                           05660000
                 'CHF_STRUCTURE',                                       05670000
                 'CHF_UNIT',                                            05680000
                 'CHF_UNIT_RELATION',                                   05690000
                 'CHF_UNIT_TYPES',                                      05700000
                 'CMT_APL_PANEL',                                       05710000
                 'CMT_LINK',                                            05720000
                 'CMT_OBJECT',                                          05730000
                 'PEI_CND_RULE',                                        05740000
                 'PEI_PRT_INTF_MDU',                                    05750000
                 'PEI_PRT_CND',                                         05760000
                 'PEI_PRT_DTA',                                         05770000
                 'PEI_PRT_RTT',                                         05780000
                 'PEI_PRT_REQ',                                         05790000
                 'PSW_COLUMNS',                                         05800000
                 'PSW_DEFAULTS',                                        05810000
                 'PSW_EDITS',                                           05820000
                 'PSW_TBL_SEC',                                         05830000
                 'PSW_SYS_SPT',                                         05840000
                 'PSW_TABLES',                                          05850000
                 'WIP_ACY_ASN_RULE',                                    05860000
                 'WIP_ACY_CHECKLIST',                                   05870000
                 'WIP_CLASS_CTRL',                                      05880000
                 'WIP_HISTORY_EVENT',                                   05890000
                 'WIP_INITIATOR',                                       05900000
                 'WIP_ACTIVITY',                                        05910000
                 'WIP_DRY_CHECKLIST',                                   05920000
                 'WIP_DRY_HISTORY',                                     05930000
                 'WIP_DIARY',                                           05940000
                 'WIP_DRY_OBJECTS',                                     05950000
                 'WIP_GROUP_AUT',                                       05960000
                 'WIP_GROUPS',                                          05970000
                 'WIP_OBJ_LOCATE',                                      05980000
                 'WIP_PRIORITY',                                        05990000
                 'WIP_STATUS',                                          06000000
                 'WKM_BUS_CASE_DEF',                                    06010000
                 'WKM_BUS_CASE_LOG',                                    06020000
                 'WKM_BUS_CASE_STP',                                    06030000
                 'WKM_CASE_STEP_DEF',                                   06040000
                 'WKM_PRODUCT_TRANS',                                   06050000
                 'DWS_ACY_COLLECTION',                                  06060000
                 'DWS_CLIENT_RULES',                                    06070000
                 'DWS_CD_TXT',                                          06080000
                 'DWS_DSB_BCH_HST',                                     06090000
                 'DWS_DSB_CLIENT',                                      06100000
                 'DWS_DISBURSEMENT',                                    06110000
                 'DWS_ERR_ACTIVITY',                                    06120000
                 'DWS_IVT_CONTROL',                                     06130000
                 'DWS_IVT_DETAIL',                                      06140000
                 'DWS_LOCATION_RULES',                                  06150000
                 'DWS_OUTPUT_FMT',                                      06160000
                 'DWS_RULE',                                            06170000
                 'DWS_STATUS_HST',                                      06180000
                 'DWS_TXT',                                             06190000
                 'ERROR_STORAGE',                                       06200000
                 'POLICY_CLIENT',                                       06210000
                 'POLICY_TAB',                                          06220000
                 'DWELLING_TAB',                                        06230000
                 'DWELLING_CLIENT',                                     06240000
                 'LEGAL_DAYS_NOTICE',                                   06250000
                 'CANC_TRIGGER',                                        06260000
                 'PINT_LATE_FEE',                                       06270000
                 'PINT_RESTART',                                        06280000
                 'PINT_CANC_FORM',                                      06290000
                 'PINT_PRODUCER_PIR',                                   06300000
                 'PINT_GL_SUMMARY',                                     06310000
                 'PINT_GL_DETAIL',                                      06320000
                 'PINT_GL_PREM_ISS',                                    06330000
                 'PINT_COMMISSION',                                     06340000
                 'PINT_GS_DETAIL',                                      06350000
                 'PINT_CHKPT_FRQ',                                      06360000
                 'PINT_ERROR_MESSAGE',                                  06370000
                 'PINT_POSTNET_BCODE',                                  06380000
                 'PINT_PREM_RCYL_EXT')                                  06390000
