SELECT CREATOR, NAME, UNIQUERULE
  FROM SYSIBM.SYSINDEXES
 WHERE NAME IN (
                'XMACPS1B',
                'XS2CAP0B',
                'XS3CAP0B',
                'XS4CAP0B',
                'XS5CAP0B',
                'XS6CAP0B',
                'XS8CAP0B',
                'XS9CAP0B',
                'XSACAP0B',
                'XSBCAP0B',
                'XSCCAP0B',
                'XSDCAP0B',
                'XSECAP0B',
                'XSFCAP0B',
                'XSGCAP0B',
                'XSHCAP0B',
                'XSICAP0B',
                'XSJCAP0B',
                'XSKCAP0B',
                'XSKCAP0H',
                'XSLCAP0B',
                'XSLCAP0H',
                'XSMCAP0B',
                'XSMCAP0H',
                'XSNCAP0B');
