SELECT
'-STOP DB('||STRIP(DBNAME)||') SP('||STRIP(TSNAME)||')'||
'  --'||STRIP(CREATOR)||'.'||STRIP(NAME)
  FROM SYSIBM.SYSTABLES
 WHERE TYPE = 'T'
   AND CREATOR IN ('DB2PRVT', 'DB2PRV2')
   AND NAME IN ('CLIENT_ADDRESS'
               ,'CLIENT_ADDRESS_V'
               ,'CLIENT_BILLING'
               ,'CLIENT_CLAIM'
               ,'CLIENT_CROSS_REF'
               ,'CLIENT_HELP'
               ,'CLIENT_KEYS'
               ,'CLIENT_LICENSE'
               ,'CLIENT_MENU'
               ,'CLIENT_PHONE'
               ,'CLIENT_POLICY'
               ,'CLIENT_POLICY_V'
               ,'CLIENT_SUMMARY'
               ,'CLIENT_TAB'
               ,'CLIENT_TAB_V'
               ,'CLIENT_TAX'
               ,'CLIENT_UCT'
               ,'CLT_ADD_ADR_TEXT'
               ,'CLT_ADD_NAME_TEXT'
               ,'CLT_ADR_RELATION'
               ,'CLT_ADR_RELATION_V'
               ,'CLT_ADR_SEARCH'
               ,'CLT_CLT_RELATION'
               ,'CLT_CLT_VLD_REL'
               ,'CLT_CONTACT_INFO'
               ,'CLT_OBJ_RELATION'
               ,'CLT_OBJ_RELATION_V'
               ,'CLT_OWNING_SYSTE_V'
               ,'CLT_OWNING_SYSTEM'
               ,'CLT_REF_RELATION'
               ,'CLT_TABLE_ID_GEN'
               ,'CLT_TEMPLATE'
               ,'CDI_DB_DUNBRAD'
               ,'CDI_PA_PARR'
               ,'CDI_SN_DBSCRUB'
               ,'CLT_TABLE_ID_GEN'
               ,'CLT_ADD_ADR_TEXT'
               ,'CLT_ADD_NAME_TEXT'
               ,'CLT_ADR_RELATION'
               ,'BUSINESS_CLIENT'
               ,'CLIENT_ADDRESS'
               ,'CLIENT_BILLING'
               ,'CLT_CONTACT_INFO'
               ,'CLIENT_TAB'
               ,'CLIENT_CLAIM'
               ,'CLT_CLT_RELATION'
               ,'HOUSEHOLD_CLIENT'
               ,'INDIVIDUAL_CLIENT'
               ,'CLT_OTHER_OBJECTS'
               ,'CLT_OBJ_RELATION'
               ,'CLIENT_POLICY'
               ,'CLT_ADR_SEARCH'
               ,'CLFT_POLICY_TERM')
;
SELECT
'-STOP DB('||STRIP(I.DBNAME)||') SP('||STRIP(I.INDEXSPACE)||')'||
'  --'||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSINDEXES I
 WHERE T.CREATOR = I.TBCREATOR
   AND T.NAME = I.TBNAME
   AND T.TYPE = 'T'
   AND T.CREATOR IN ('DB2PRVT', 'DB2PRV2')
   AND T.NAME IN ('CLIENT_ADDRESS'
               ,'CLIENT_ADDRESS_V'
               ,'CLIENT_BILLING'
               ,'CLIENT_CLAIM'
               ,'CLIENT_CROSS_REF'
               ,'CLIENT_HELP'
               ,'CLIENT_KEYS'
               ,'CLIENT_LICENSE'
               ,'CLIENT_MENU'
               ,'CLIENT_PHONE'
               ,'CLIENT_POLICY'
               ,'CLIENT_POLICY_V'
               ,'CLIENT_SUMMARY'
               ,'CLIENT_TAB'
               ,'CLIENT_TAB_V'
               ,'CLIENT_TAX'
               ,'CLIENT_UCT'
               ,'CLT_ADD_ADR_TEXT'
               ,'CLT_ADD_NAME_TEXT'
               ,'CLT_ADR_RELATION'
               ,'CLT_ADR_RELATION_V'
               ,'CLT_ADR_SEARCH'
               ,'CLT_CLT_RELATION'
               ,'CLT_CLT_VLD_REL'
               ,'CLT_CONTACT_INFO'
               ,'CLT_OBJ_RELATION'
               ,'CLT_OBJ_RELATION_V'
               ,'CLT_OWNING_SYSTE_V'
               ,'CLT_OWNING_SYSTEM'
               ,'CLT_REF_RELATION'
               ,'CLT_TABLE_ID_GEN'
               ,'CLT_TEMPLATE'
               ,'CDI_DB_DUNBRAD'
               ,'CDI_PA_PARR'
               ,'CDI_SN_DBSCRUB'
               ,'CLT_TABLE_ID_GEN'
               ,'CLT_ADD_ADR_TEXT'
               ,'CLT_ADD_NAME_TEXT'
               ,'CLT_ADR_RELATION'
               ,'BUSINESS_CLIENT'
               ,'CLIENT_ADDRESS'
               ,'CLIENT_BILLING'
               ,'CLT_CONTACT_INFO'
               ,'CLIENT_TAB'
               ,'CLIENT_CLAIM'
               ,'CLT_CLT_RELATION'
               ,'HOUSEHOLD_CLIENT'
               ,'INDIVIDUAL_CLIENT'
               ,'CLT_OTHER_OBJECTS'
               ,'CLT_OBJ_RELATION'
               ,'CLIENT_POLICY'
               ,'CLT_ADR_SEARCH'
               ,'CLFT_POLICY_TERM')
