SELECT SUM (TOTAL) FROM (
SELECT 'DB2Q', JOBNAME, MAX(ICDATE) AS LAST_BKP, COUNT(*) AS TOTAL
FROM SYSIBM.SYSCOPY
WHERE ICTYPE = 'F' AND TIMESTAMP >=(CURRENT_TIMESTAMP - 30 DAYS)
AND DBNAME NOT IN ('DLCDB   ', 'CC390 '  )
AND  JOBNAME NOT LIKE 'IBM1%'
AND   DBNAME NOT LIKE 'BMC%'
AND   DBNAME NOT LIKE 'DSN%'
AND   DBNAME NOT LIKE 'SYS%'
AND   DBNAME NOT LIKE 'DB2%'
AND   DBNAME NOT LIKE 'DBA%'
GROUP BY JOBNAME ) AS C2;
