SELECT 'DB2E',A.DBNAME, A.TSNAME,
     MAX(A.PARTITION),B.TYPE, B.DSSIZE, A.COMPRESS
  FROM SYSIBM.SYSTABLEPART A
           , SYSIBM.SYSTABLESPACE B
 WHERE A.DBNAME = B.DBNAME
   AND A.TSNAME = B.NAME
   AND B.PARTITIONS > 0
GROUP BY 'DB2P',A.DBNAME, A.TSNAME,
B.TYPE,B.DSSIZE, B.PARTITIONS, A.COMPRESS
;
