SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';DBADM;'
       FROM SYSIBM.SYSDBAUTH WHERE
DBADMAUTH  IN('Y','G')
UNION SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';DBCTRL;'
       FROM SYSIBM.SYSDBAUTH WHERE
DBCTRLAUTH IN('Y','G')  AND DBADMAUTH = ' '
UNION SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';DBMAINT;'
       FROM SYSIBM.SYSDBAUTH WHERE
DBMAINTAUTH IN('Y','G')  AND DBADMAUTH = ' ' AND DBCTRLAUTH = ' '
UNION SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';LOAD;'
       FROM SYSIBM.SYSDBAUTH WHERE
LOADAUTH    IN('Y','G')  AND DBADMAUTH = ' ' AND DBCTRLAUTH = ' '
       AND DBMAINTAUTH  = ' '
UNION SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';DROP;'
       FROM SYSIBM.SYSDBAUTH WHERE
DROPAUTH    IN('Y','G')  AND DBADMAUTH = ' ' AND DBCTRLAUTH = ' '
       AND DBMAINTAUTH  = ' ' AND LOADAUTH = ' '
UNION SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';RECOVERDB;'
       FROM SYSIBM.SYSDBAUTH WHERE
RECOVERDBAUTH    IN('Y','G')  AND DBADMAUTH = ' ' AND DBCTRLAUTH = ' '
       AND DBMAINTAUTH  = ' ' AND LOADAUTH = ' ' AND DROPAUTH = ' '
UNION SELECT
         'DB2Q;'||GRANTEE||';'||NAME||';REPAIR;'
       FROM SYSIBM.SYSDBAUTH WHERE
REPAIRAUTH  IN('Y','G')  AND DBADMAUTH = ' ' AND DBCTRLAUTH = ' '
       AND DBMAINTAUTH  = ' ' AND LOADAUTH = ' ' AND DROPAUTH = ' '
       AND RECOVERDBAUTH = ' '
UNION SELECT
    'DB2Q;'||GRANTEE||';;SYSADM;'
  FROM SYSIBM.SYSUSERAUTH WHERE  SYSADMAUTH IN('Y','G')
UNION     SELECT
    'DB2Q;'||GRANTEE||';;SYSCTRL;'
  FROM SYSIBM.SYSUSERAUTH WHERE  SYSCTRLAUTH IN('Y','G')
UNION SELECT
    'DB2Q;'||GRANTEE||';;SYSOPER;'
  FROM SYSIBM.SYSUSERAUTH WHERE  SYSOPRAUTH IN('Y','G')
