SELECT NAME,  STRIP(TBCREATOR)||'.'||TBNAME AS TBL,                     00001002
       'DB2Q' AS SUBSYS                                                 00001109
 FROM SYSIBM.SYSCOLUMNS                                                 00002001
 WHERE TBCREATOR <> 'SYSIBM'                                            00004001
   AND NAME IN                                                          00005001
               ('ADD',                                                  00010001
                'AFTER',                                                00020001
                'ALL',                                                  00030001
                'ALLOCATE',                                             00040001
                'ALLOW',                                                00050001
                'ALTER',                                                00060001
                'AND',                                                  00070001
                'ANY',                                                  00080001
                'AS',                                                   00090001
                'ASENSITIVE',                                           00100001
                'ASSOCIATE',                                            00110001
                'ASUTIME',                                              00120001
                'AT',                                                   00130001
                'AUDIT',                                                00140001
                'AUX',                                                  00150001
                'AUXILIARY',                                            00160001
                'BEFORE',                                               00170001
                'BEGIN',                                                00180001
                'BETWEEN',                                              00190001
                'BUFFERPOOL',                                           00200001
                'BY',                                                   00210001
                'CALL',                                                 00220001
                'CAPTURE',                                              00230001
                'CASCADED',                                             00240001
                'CASE',                                                 00250001
                'CAST',                                                 00260001
                'CCSID',                                                00270001
                'CHAR',                                                 00280001
                'CHARACTER',                                            00290001
                'CHECK',                                                00300001
                'CLONE',                                                00310001
                'CLOSE',                                                00320001
                'CLUSTER',                                              00330001
                'COLLECTION',                                           00340001
                'COLLID',                                               00350001
                'COLUMN',                                               00360001
                'COMMENT',                                              00370001
                'COMMIT',                                               00380001
                'CONCAT',                                               00390001
                'CONDITION',                                            00400001
                'CONNECT',                                              00410001
                'CONNECTION',                                           00420001
                'CONSTRAINT',                                           00430001
                'CONTAINS',                                             00440001
                'CONTENT',                                              00450001
                'CONTINUE',                                             00460001
                'CREATE',                                               00470001
                'CURRENT',                                              00480001
                'CURRENT_DATE',                                         00490001
                'CURRENT_LC_CTYPE',                                     00500001
                'CURRENT_PATH',                                         00510001
                'CURRENT_SCHEMA',                                       00520001
                'CURRENT_TIME',                                         00530001
                'CURRENT_TIMESTAMP',                                    00540001
                'CURSOR',                                               00550001
                'DATA',                                                 00560001
                'DATABASE',                                             00570001
                'DAY',                                                  00580001
                'DAYS',                                                 00590001
                'DBINFO',                                               00600001
                'DECLARE',                                              00610001
                'DEFAULT',                                              00620001
                'DELETE',                                               00630001
                'DESCRIPTOR',                                           00640001
                'DETERMINISTIC',                                        00650001
                'DISABLE',                                              00660001
                'DISALLOW',                                             00670001
                'DISTINCT',                                             00680001
                'DO',                                                   00690001
                'DOCUMENT',                                             00700001
                'DOUBLE',                                               00710001
                'DROP',                                                 00720001
                'DSSIZE',                                               00730001
                'DYNAMIC',                                              00740001
                'EDITPROC',                                             00750001
                'ELSE',                                                 00760001
                'ELSEIF',                                               00770001
                'ENCODING',                                             00780001
                'ENCRYPTION',                                           00790001
                'END',                                                  00800001
                'END-EXEC',                                             00810001
                'ENDING',                                               00820001
                'ERASE',                                                00830001
                'ESCAPE',                                               00840001
                'EXCEPT',                                               00850001
                'EXCEPTION',                                            00860001
                'EXECUTE',                                              00870001
                'EXISTS',                                               00880001
                'EXIT',                                                 00890001
                'EXPLAIN',                                              00900001
                'EXTERNAL',                                             00910001
                'FENCED',                                               00920001
                'FETCH',                                                00930001
                'FIELDPROC',                                            00940001
                'FINAL',                                                00950001
                'FOR',                                                  00960001
                'FREE',                                                 00970001
                'FROM',                                                 00980001
                'FULL',                                                 00990001
                'FUNCTION',                                             01000001
                'GENERATED',                                            01010001
                'GET',                                                  01020001
                'GLOBAL',                                               01030001
                'GO',                                                   01040001
                'GOTO',                                                 01050001
                'GRANT',                                                01060001
                'GROUP',                                                01070001
                'HANDLER',                                              01080001
                'HAVING',                                               01090001
                'HOLD',                                                 01100001
                'HOUR',                                                 01110001
                'HOURS',                                                01120001
                'IF',                                                   01130001
                'IMMEDIATE',                                            01140001
                'IN',                                                   01150001
                'INCLUSIVE',                                            01160001
                'INDEX',                                                01170001
                'INHERIT',                                              01180001
                'INNER',                                                01190001
                'INOUT',                                                01200001
                'INSENSITIVE',                                          01210001
                'INSERT',                                               01220001
                'INTERSECT',                                            01230001
                'INTO',                                                 01240001
                'IS',                                                   01250001
                'ISOBID',                                               01260001
                'ITERATE',                                              01270001
                'JAR',                                                  01280001
                'JOIN',                                                 01290001
                'KEEP',                                                 01300001
                'KEY',                                                  01310001
                'LABEL',                                                01320001
                'LANGUAGE',                                             01330001
                'LC_CTYPE',                                             01340001
                'LEAVE',                                                01350001
                'LEFT',                                                 01360001
                'LIKE',                                                 01370001
                'LOCAL',                                                01380001
                'LOCALE',                                               01390001
                'LOCATOR',                                              01400001
                'LOCATORS',                                             01410001
                'LOCK',                                                 01420001
                'LOCKMAX',                                              01430001
                'LOCKSIZE',                                             01440001
                'LONG',                                                 01450001
                'LOOP',                                                 01460001
                'MAINTAINED',                                           01470001
                'MATERIALIZED',                                         01480001
                'MICROSECOND',                                          01490001
                'MICROSECONDS',                                         01500001
                'MINUTE',                                               01510001
                'MINUTES',                                              01520001
                'MODIFIES',                                             01530001
                'MONTH',                                                01540001
                'MONTHS',                                               01550001
                'NEXTVAL',                                              01560001
                'NO',                                                   01570001
                'NONE',                                                 01580001
                'NOT',                                                  01590001
                'NULL',                                                 01600001
                'NULLS',                                                01610001
                'NUMPARTS',                                             01620001
                'OBID',                                                 01630001
                'OF',                                                   01640001
                'ON',                                                   01650001
                'OPEN',                                                 01660001
                'OPTIMIZATION',                                         01670001
                'OPTIMIZE',                                             01680001
                'OR',                                                   01690001
                'ORDER',                                                01700001
                'OUT',                                                  01710001
                'OUTER',                                                01720001
                'PACKAGE',                                              01730001
                'PADDED',                                               01740001
                'PARAMETER',                                            01750001
                'PART',                                                 01760001
                'PARTITION',                                            01770001
                'PARTITIONED',                                          01780001
                'PARTITIONING',                                         01790001
                'PATH',                                                 01800001
                'PIECESIZE',                                            01810001
                'PLAN',                                                 01820001
                'PRECISION',                                            01830001
                'PREPARE',                                              01840001
                'PREVVAL',                                              01850001
                'PRIQTY',                                               01860001
                'PRIVILEGES',                                           01870001
                'PROCEDURE',                                            01880001
                'PROGRAM',                                              01890001
                'PSID',                                                 01900001
                'PUBLIC',                                               01910001
                'QUERY',                                                01920001
                'QUERYNO',                                              01930001
                'READS',                                                01940001
                'REFERENCES',                                           01950001
                'REFRESH',                                              01960001
                'RELEASE',                                              01970001
                'RENAME',                                               01980001
                'REPEAT',                                               01990001
                'RESIGNAL',                                             02000001
                'RESTRICT',                                             02010001
                'RESULT',                                               02020001
                'RESULT_SET_LOCATOR',                                   02030001
                'RETURN',                                               02040001
                'RETURNS',                                              02050001
                'REVOKE',                                               02060001
                'RIGHT',                                                02070001
                'ROLE',                                                 02080001
                'ROLLBACK',                                             02090001
                'ROUND_CEILING',                                        02100001
                'ROUND_DOWN',                                           02110001
                'ROUND_FLOOR',                                          02120001
                'ROUND_HALF_DOWN',                                      02130001
                'ROUND_HALF_EVEN',                                      02140001
                'ROUND_HALF_UP',                                        02150001
                'ROUND_UP',                                             02160001
                'ROW',                                                  02170001
                'ROWSET',                                               02180001
                'RUN',                                                  02190001
                'SAVEPOINT',                                            02200001
                'SCHEMA',                                               02210001
                'SCRATCHPAD',                                           02220001
                'SECOND',                                               02230001
                'SECONDS',                                              02240001
                'SECQTY',                                               02250001
                'SECURITY',                                             02260001
                'SELECT',                                               02270001
                'SENSITIVE',                                            02280001
                'SEQUENCE',                                             02290001
                'SESSION_USER',                                         02300001
                'SET',                                                  02310001
                'SIGNAL',                                               02320001
                'SIMPLE',                                               02330001
                'SOME',                                                 02340001
                'SOURCE',                                               02350001
                'SPECIFIC',                                             02360001
                'STANDARD',                                             02370001
                'STATEMENT',                                            02380001
                'STATIC',                                               02390001
                'STAY',                                                 02400001
                'STOGROUP',                                             02410001
                'STORES',                                               02420001
                'STYLE',                                                02430001
                'SUMMARY',                                              02440001
                'SYNONYM',                                              02450001
                'TABLE',                                                02460001
                'TABLESPACE',                                           02470001
                'THEN',                                                 02480001
                'TO',                                                   02490001
                'TRIGGER',                                              02500001
                'TRUNCATE',                                             02510001
                'TYPE',                                                 02520001
                'UNDO',                                                 02530001
                'UNION',                                                02540001
                'UNIQUE',                                               02550001
                'UNTIL',                                                02560001
                'UPDATE',                                               02570001
                'USER',                                                 02580001
                'USING',                                                02590001
                'VALIDPROC',                                            02600001
                'VALUE',                                                02610001
                'VALUES',                                               02620001
                'VARIABLE',                                             02630001
                'VARIANT',                                              02640001
                'VCAT',                                                 02650001
                'VIEW',                                                 02660001
                'VOLATILE',                                             02670001
                'VOLUMES',                                              02680001
                'WHEN',                                                 02690001
                'WHENEVER',                                             02700001
                'WHERE',                                                02710001
                'WHILE',                                                02720001
                'WITH',                                                 02730001
                'WLM',                                                  02740001
                'XMLCAST',                                              02750001
                'XMLEXISTS',                                            02760001
                'XMLNAMESPACES',                                        02770001
                'YEAR',                                                 02780001
                'YEARS')                                                02790001
