SELECT DISTINCT A.JOBNAME, MAX(A.ICDATE)
--SELECT DISTINCT A.DBNAME, A.TSNAME, A.JOBNAME
--       ,STRIP(B.CREATOR)||'.'||STRIP(B.NAME)
  FROM SYSIBM.SYSCOPY A,
       SYSIBM.SYSTABLES B
 WHERE B.TYPE = 'T'
   AND B.DBNAME = A.DBNAME
   AND B.TSNAME = A.TSNAME
   AND STRIP(B.CREATOR)||'.'||STRIP(B.NAME) IN (
       'FINPROD.PRIDE_AUDIT'
     , 'FINPROD.PRIDE_EMF_DATA'
     , 'FINPROD.PRIDE_EMF_STATUS'
     , 'FINPROD.PRO_LICNSE_ACTIVTY'
       )
  GROUP BY A.JOBNAME
;
SELECT DISTINCT JOBNAME, MAX(ICDATE)
  FROM SYSIBM.SYSCOPY
 WHERE DBNAME = 'D7APDV01'
  GROUP BY JOBNAME
;
SELECT DBNAME,COUNT(*)
  FROM SYSIBM.SYSTABLESPACE
 WHERE DBNAME IN (
                             'D7APDV01'
                 )
 GROUP BY DBNAME
;
SELECT DBNAME,CREATOR,NAME
  FROM SYSIBM.SYSTABLES
 WHERE DBNAME IN (
                             'D7APDV01'
                 )
;
  WHERE DBNAME LIKE 'D7%'
 GROUP BY DBNAME
;
