--
-- LISTA DOS DATABASES
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       T.DBNAME
  FROM SYSIBM.SYSTABLES T
 WHERE T.TYPE = 'T'
   AND T.CREATOR IN ('DB2ACPT','DB2ACP2','DB2ACP4','DB2CERT')
   AND T.NAME IN (
'CLIENT_ADDRESS'  ,
'CLIENT_BILLING'  ,
'CLIENT_CLAIM'    ,
'CLIENT_CROSS_REF',
'CLIENT_HELP'     ,
'CLIENT_KEYS'     ,
'CLIENT_LICENSE'  ,
'CLIENT_MENU'     ,
'CLIENT_PHONE'    ,
'CLIENT_POLICY'   ,
'CLIENT_SUMMARY'  ,
'CLIENT_TAB'      ,
'CLIENT_TAX'      ,
'CLIENT_UCT'      ,
'CLT_ADD_ADR_TEXT',
'CLT_ADR_RELATION',
'CLT_ADR_SEARCH'  ,
'CLT_CLT_RELATION',
'CLT_CLT_VLD_REL' ,
'CLT_CONTACT_INFO',
'CLT_OBJ_RELATION',
'CLT_OWNING_SYSTEM',
'CLT_REF_RELATION',
'CLT_TABLE_ID_GEN',
'CLT_TEMPLATE'    ,
'CDI_DB_DUNBRAD'  ,
'CDI_PA_PARR'     ,
'CDI_SN_DBSCRUB'  ,
'CLT_TABLE_ID_GEN',
'CLT_ADD_ADR_TEXT',
'CLT_ADD_NAME_TEXT',
'CLT_ADR_RELATION' ,
'BUSINESS_CLIENT'  ,
'CLIENT_ADDRESS'   ,
'CLIENT_BILLING'   ,
'CLT_CONTACT_INFO' ,
'CLIENT_TAB'       ,
'CLIENT_CLAIM'     ,
'CLT_CLT_RELATION' ,
'HOUSEHOLD_CLIENT' ,
'INDIVIDUAL_CLIENT',
'CLT_OTHER_OBJECTS',
'CLT_OBJ_RELATION' ,
'CLIENT_POLICY'    ,
'CLT_ADR_SEARCH'   ,
'CLFT_POLICY_TERM'
);

--
-- LISTA JOBS NA SYSCOPY
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       JOBNAME
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSCOPY C
 WHERE T.DBNAME = C.DBNAME
   AND T.TSNAME = C.TSNAME
   AND C.ICTYPE = 'F'
   AND T.TYPE = 'T'
   AND C.TIMESTAMP >= CURRENT TIMESTAMP - 45 DAYS
   AND T.CREATOR IN ('DB2ACPT','DB2ACP2','DB2ACP4','DB2CERT')
   AND T.NAME IN (
'CLIENT_ADDRESS'  ,
'CLIENT_BILLING'  ,
'CLIENT_CLAIM'    ,
'CLIENT_CROSS_REF',
'CLIENT_HELP'     ,
'CLIENT_KEYS'     ,
'CLIENT_LICENSE'  ,
'CLIENT_MENU'     ,
'CLIENT_PHONE'    ,
'CLIENT_POLICY'   ,
'CLIENT_SUMMARY'  ,
'CLIENT_TAB'      ,
'CLIENT_TAX'      ,
'CLIENT_UCT'      ,
'CLT_ADD_ADR_TEXT',
'CLT_ADR_RELATION',
'CLT_ADR_SEARCH'  ,
'CLT_CLT_RELATION',
'CLT_CLT_VLD_REL' ,
'CLT_CONTACT_INFO',
'CLT_OBJ_RELATION',
'CLT_OWNING_SYSTEM',
'CLT_REF_RELATION',
'CLT_TABLE_ID_GEN',
'CLT_TEMPLATE'    ,
'CDI_DB_DUNBRAD'  ,
'CDI_PA_PARR'     ,
'CDI_SN_DBSCRUB'  ,
'CLT_TABLE_ID_GEN',
'CLT_ADD_ADR_TEXT',
'CLT_ADD_NAME_TEXT',
'CLT_ADR_RELATION' ,
'BUSINESS_CLIENT'  ,
'CLIENT_ADDRESS'   ,
'CLIENT_BILLING'   ,
'CLT_CONTACT_INFO' ,
'CLIENT_TAB'       ,
'CLIENT_CLAIM'     ,
'CLT_CLT_RELATION' ,
'HOUSEHOLD_CLIENT' ,
'INDIVIDUAL_CLIENT',
'CLT_OTHER_OBJECTS',
'CLT_OBJ_RELATION' ,
'CLIENT_POLICY'    ,
'CLT_ADR_SEARCH'   ,
'CLFT_POLICY_TERM'
);


--
-- GENERATE INCLUDES
--
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'INCLUDE TABLESPACE '||
       STRIP(T.DBNAME)||'.'||STRIP(T.TSNAME)||
' -- '||STRIP(T.CREATOR)||'.'||STRIP(T.NAME),
S.NTABLES
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABLESPACE S
 WHERE T.DBNAME = S.DBNAME
   AND T.TSNAME = S.NAME
   AND T.TYPE = 'T'
   AND T.CREATOR IN ('DB2ACPT','DB2ACP2','DB2ACP4','DB2CERT')
   AND T.NAME IN (
'CLIENT_ADDRESS'  ,
'CLIENT_BILLING'  ,
'CLIENT_CLAIM'    ,
'CLIENT_CROSS_REF',
'CLIENT_HELP'     ,
'CLIENT_KEYS'     ,
'CLIENT_LICENSE'  ,
'CLIENT_MENU'     ,
'CLIENT_PHONE'    ,
'CLIENT_POLICY'   ,
'CLIENT_SUMMARY'  ,
'CLIENT_TAB'      ,
'CLIENT_TAX'      ,
'CLIENT_UCT'      ,
'CLT_ADD_ADR_TEXT',
'CLT_ADR_RELATION',
'CLT_ADR_SEARCH'  ,
'CLT_CLT_RELATION',
'CLT_CLT_VLD_REL' ,
'CLT_CONTACT_INFO',
'CLT_OBJ_RELATION',
'CLT_OWNING_SYSTEM',
'CLT_REF_RELATION',
'CLT_TABLE_ID_GEN',
'CLT_TEMPLATE'    ,
'CDI_DB_DUNBRAD'  ,
'CDI_PA_PARR'     ,
'CDI_SN_DBSCRUB'  ,
'CLT_TABLE_ID_GEN',
'CLT_ADD_ADR_TEXT',
'CLT_ADD_NAME_TEXT',
'CLT_ADR_RELATION' ,
'BUSINESS_CLIENT'  ,
'CLIENT_ADDRESS'   ,
'CLIENT_BILLING'   ,
'CLT_CONTACT_INFO' ,
'CLIENT_TAB'       ,
'CLIENT_CLAIM'     ,
'CLT_CLT_RELATION' ,
'HOUSEHOLD_CLIENT' ,
'INDIVIDUAL_CLIENT',
'CLT_OTHER_OBJECTS',
'CLT_OBJ_RELATION' ,
'CLIENT_POLICY'    ,
'CLT_ADR_SEARCH'   ,
'CLFT_POLICY_TERM'
);


--
-- GEN
--
--DB='DQST0B00', TS='SCCS0B00';
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'DB='||''''||
       STRIP(T.DBNAME)||''''||', TS='||''''||
       STRIP(T.TSNAME)||''''||';'
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABLESPACE S
 WHERE T.DBNAME = S.DBNAME
   AND T.TSNAME = S.NAME
   AND T.TYPE = 'T'
   AND T.CREATOR IN ('DB2ACPT','DB2ACP2','DB2ACP4','DB2CERT')
   AND T.NAME IN (
'CLIENT_ADDRESS'  ,
'CLIENT_BILLING'  ,
'CLIENT_CLAIM'    ,
'CLIENT_CROSS_REF',
'CLIENT_HELP'     ,
'CLIENT_KEYS'     ,
'CLIENT_LICENSE'  ,
'CLIENT_MENU'     ,
'CLIENT_PHONE'    ,
'CLIENT_POLICY'   ,
'CLIENT_SUMMARY'  ,
'CLIENT_TAB'      ,
'CLIENT_TAX'      ,
'CLIENT_UCT'      ,
'CLT_ADD_ADR_TEXT',
'CLT_ADR_RELATION',
'CLT_ADR_SEARCH'  ,
'CLT_CLT_RELATION',
'CLT_CLT_VLD_REL' ,
'CLT_CONTACT_INFO',
'CLT_OBJ_RELATION',
'CLT_OWNING_SYSTEM',
'CLT_REF_RELATION',
'CLT_TABLE_ID_GEN',
'CLT_TEMPLATE'    ,
'CDI_DB_DUNBRAD'  ,
'CDI_PA_PARR'     ,
'CDI_SN_DBSCRUB'  ,
'CLT_TABLE_ID_GEN',
'CLT_ADD_ADR_TEXT',
'CLT_ADD_NAME_TEXT',
'CLT_ADR_RELATION' ,
'BUSINESS_CLIENT'  ,
'CLIENT_ADDRESS'   ,
'CLIENT_BILLING'   ,
'CLT_CONTACT_INFO' ,
'CLIENT_TAB'       ,
'CLIENT_CLAIM'     ,
'CLT_CLT_RELATION' ,
'HOUSEHOLD_CLIENT' ,
'INDIVIDUAL_CLIENT',
'CLT_OTHER_OBJECTS',
'CLT_OBJ_RELATION' ,
'CLIENT_POLICY'    ,
'CLT_ADR_SEARCH'   ,
'CLFT_POLICY_TERM'
);



--
-- FREE PLAN
--
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'FREE PLAN ('||STRIP(NAME)||')'
  FROM SYSIBM.SYSPLAN
--WHERE STRIP(CREATOR)||'.'||STRIP(NAME)  IN (
WHERE STRIP(NAME)  IN (
'CDIPMARA',
'CDIPMARB',
'CDIPMARI',
'CDICMARA',
'CDICMARB',
'CDICMARI',
'CDITBILL',
'CDITEXP1',
'CLIPBTCH',
'CD2CMARB',
'CD2CMARI',
'CD5CMARB',
'CD5CMARI',
'CD6CMARB',
'CD6CMARI',
'CD4PMARA',
'CD4PMARE',
'CD4PMARF',
'CD4PMARI',
'CD4PMARJ',
'CD4PMARP'
);


--
-- FREE PACKAGE
--
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'FREE PACKAGE ('||STRIP(COLLID)||'.'||STRIP(NAME)||')'
  FROM SYSIBM.SYSPACKAGE
--WHERE STRIP(COLLID)||'.'||STRIP(NAME) IN (
WHERE STRIP(NAME) IN (
'CLI7BTCH',
'CLI7UPRM',
'CLI7NSPO',
'CLI7B900',
'CLI7LUTL',
'CLI7GCLT',
'CLI7RUN',
'CLI7UCLT',
'CL7COMP',
'CL7DBDEL',
'CL7OBJUP',
'CL7POLCY',
'CDIOCHK',
'CDIODAT8',
'CDIOF07' ,
'CDIOF08' ,
'CDIOF17' ,
'CDIOO02X',
'CDIOSRB' ,
'CDITADRN',
'CDITASEQ',
'CDITBPTI',
'CDITBPTU',
'CDITFFID',
'CDITGNAC',
'CDITGNCU',
'CDITLEGL',
'CDITNCHA',
'CDITNCHG',
'CDITNEOT',
'CDITNSRT',
'CDITPROD',
'CDITREAD',
'CDITREF' ,
'CDITREOD',
'CDITREOP',
'CDITRESP',
'CDITSABS',
'CDITSDBS',
'CDITSEOH',
'CDITSRCH',
'CDITUEOT',
'CDITUPDT'
);

--
-- DROP TABLESPACE
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
'DROP TABLESPACE '||STRIP(T.DBNAME)||'.'||STRIP(T.TSNAME)||
'; -- '||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)
  FROM SYSIBM.SYSTABLES T
 WHERE T.TYPE = 'T'
--   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   AND T.CREATOR IN ('DB2ACPT','DB2ACP2','DB2ACP4','DB2CERT')
   AND T.NAME IN (
'CLIENT_ADDRESS'  ,
'CLIENT_BILLING'  ,
'CLIENT_CLAIM'    ,
'CLIENT_CROSS_REF',
'CLIENT_HELP'     ,
'CLIENT_KEYS'     ,
'CLIENT_LICENSE'  ,
'CLIENT_MENU'     ,
'CLIENT_PHONE'    ,
'CLIENT_POLICY'   ,
'CLIENT_SUMMARY'  ,
'CLIENT_TAB'      ,
'CLIENT_TAX'      ,
'CLIENT_UCT'      ,
'CLT_ADD_ADR_TEXT',
'CLT_ADR_RELATION',
'CLT_ADR_SEARCH'  ,
'CLT_CLT_RELATION',
'CLT_CLT_VLD_REL' ,
'CLT_CONTACT_INFO',
'CLT_OBJ_RELATION',
'CLT_OWNING_SYSTEM',
'CLT_REF_RELATION',
'CLT_TABLE_ID_GEN',
'CLT_TEMPLATE'    ,
'CDI_DB_DUNBRAD'  ,
'CDI_PA_PARR'     ,
'CDI_SN_DBSCRUB'  ,
'CLT_TABLE_ID_GEN',
'CLT_ADD_ADR_TEXT',
'CLT_ADD_NAME_TEXT',
'CLT_ADR_RELATION' ,
'BUSINESS_CLIENT'  ,
'CLIENT_ADDRESS'   ,
'CLIENT_BILLING'   ,
'CLT_CONTACT_INFO' ,
'CLIENT_TAB'       ,
'CLIENT_CLAIM'     ,
'CLT_CLT_RELATION' ,
'HOUSEHOLD_CLIENT' ,
'INDIVIDUAL_CLIENT',
'CLT_OTHER_OBJECTS',
'CLT_OBJ_RELATION' ,
'CLIENT_POLICY'    ,
'CLT_ADR_SEARCH'   ,
'CLFT_POLICY_TERM'
);

