--
-- REVOKE ACCESS
-- REVOKE ALL ON CREATOR.NAME FROM USERID BY ALL;
--
SELECT DISTINCT
CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID ,
'REVOKE ALL ON '||STRIP(T.CREATOR)||'.'||STRIP(TA.TTNAME)||
' FROM '||STRIP(TA.GRANTEE)||' BY ALL;'
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABAUTH TA
 WHERE T.CREATOR = TA.TCREATOR
   AND T.NAME = TA.TTNAME
   AND T.TYPE = 'T'
   AND TA.GRANTEE <> T.CREATOR
   AND TA.GRANTEETYPE = ' '
-- AND 'G' IN (TA.DELETEAUTH,TA.INSERTAUTH,TA.UPDATEAUTH,TA.SELECTAUTH)
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;
--
-- LISTA JOBS NA SYSCOPY
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       JOBNAME,C.ICTYPE
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSCOPY C
 WHERE T.DBNAME = C.DBNAME
   AND T.TSNAME = C.TSNAME
   AND C.ICTYPE IN ('F', 'Q')
   AND T.TYPE = 'T'
   AND C.TIMESTAMP >= CURRENT TIMESTAMP - 45 DAYS
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;
--
-- STOP TS E IX
--

SELECT DISTINCT
CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID ,S.NTABLES,
'-STOP DB('||STRIP(T.DBNAME)||') SP('||STRIP(T.TSNAME)||')'
-- ||'  --'||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABLESPACE S
 WHERE T.DBNAME = S.DBNAME
   AND T.TSNAME = S.NAME
   AND T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;
SELECT DISTINCT
CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
'-STOP DB('||STRIP(I.DBNAME)||') SP('||STRIP(I.INDEXSPACE)||')'
--||'  --'||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSINDEXES I
 WHERE T.CREATOR = I.TBCREATOR
   AND T.NAME = I.TBNAME
   AND T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;

--
-- GENERATE INCLUDES
--
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'INCLUDE TABLESPACE '||
       STRIP(T.DBNAME)||'.'||STRIP(T.TSNAME)||
       ' -- '||STRIP(T.CREATOR)||'.'||STRIP(T.NAME),
       S.NTABLES,T.TYPE
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABLESPACE S
 WHERE T.DBNAME = S.DBNAME
   AND T.TSNAME = S.NAME
   AND T.TYPE IN ('T','A','V')
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
ORDER BY T.TYPE
;

--
-- GEN TS
--
--DB='DQST0B00', TS='SCCS0B00';
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'DB='||''''||
       STRIP(T.DBNAME)||''''||', TS='||''''||
       STRIP(T.TSNAME)||''''||';'
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABLESPACE S
 WHERE T.DBNAME = S.DBNAME
   AND T.TSNAME = S.NAME
   AND T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;

--
-- GEN TABLE
--
--OWN='DB2ACP2',TB='CLUB_MEM_INFO';
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'OWN='||''''||
       STRIP(T.CREATOR)||''''||',TB='||''''||
       STRIP(T.NAME)||''''||';'
  FROM SYSIBM.SYSTABLES T,
       SYSIBM.SYSTABLESPACE S
 WHERE T.DBNAME = S.DBNAME
   AND T.TSNAME = S.NAME
   AND T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;

--
-- DROP TABLESPACE
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
'DROP TABLESPACE '||STRIP(T.DBNAME)||'.'||STRIP(T.TSNAME)||
'; -- '||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)
  FROM SYSIBM.SYSTABLES T
 WHERE T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;

--
-- DROP TABLE
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
'DROP TABLE '||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)||
'; -- '||STRIP(T.CREATOR)||'.'||STRIP(T.NAME)
  FROM SYSIBM.SYSTABLES T
 WHERE T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;

--
-- DISTINCT DATABASES - CHECK EMPTY DATABASES
--

SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
T.DBNAME
  FROM SYSIBM.SYSTABLES T
 WHERE T.TYPE = 'T'
   AND STRIP(T.CREATOR)||'.'||STRIP(T.NAME) IN (
   'PERPROD.CLIENT_ADDRESS',
   'PERPROD.CLIENT_ADDRESS_V',
   'PERPROD.CLIENT_BILLING',
   'PERPROD.CLIENT_CLAIM',
   'PERPROD.CLIENT_CROSS_REF',
   'PERPROD.CLIENT_HELP',
   'PERPROD.CLIENT_KEYS',
   'PERPROD.CLIENT_LICENSE',
   'PERPROD.CLIENT_MENU',
   'PERPROD.CLIENT_PHONE',
   'PERPROD.CLIENT_POLICY',
   'PERPROD.CLIENT_POLICY_V',
   'PERPROD.CLIENT_SUMMARY',
   'PERPROD.CLIENT_TAB',
   'PERPROD.CLIENT_TAB_V',
   'PERPROD.CLIENT_TAX',
   'PERPROD.CLIENT_UCT',
   'PERPROD.CLT_ADD_ADR_TEXT',
   'PERPROD.CLT_ADD_NAME_TEXT',
   'PERPROD.CLT_ADR_RELATION',
   'PERPROD.CLT_ADR_RELATION_V',
   'PERPROD.CLT_ADR_SEARCH',
   'PERPROD.CLT_CLT_RELATION',
   'PERPROD.CLT_CLT_VLD_REL',
   'PERPROD.CLT_CONTACT_INFO',
   'PERPROD.CLT_OBJ_RELATION',
   'PERPROD.CLT_OBJ_RELATION_V',
   'PERPROD.CLT_OTHER_OBJECTS',
   'PERPROD.CLT_OWNING_SYSTE_V',
   'PERPROD.CLT_OWNING_SYSTEM',
   'PERPROD.CLT_REF_RELATION',
   'PERPROD.CLT_TABLE_ID_GEN',
   'PERPROD.CLT_TEMPLATE',
   'PERPROD.ARCH_LOK_RON',
   'PERPROD.ARCH_LOK_RON_V',
   'PERPROD.ARCH_LOK_RUP',
   'PERPROD.ARCH_LOK_RUP_V',
   'PERPROD.CLUB_MEM_INFO')
;
--
-- FREE PACKAGE
--
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'FREE PACKAGE ('||STRIP(COLLID)||'.'||STRIP(NAME)||')'
  FROM SYSIBM.SYSPACKAGE
--WHERE STRIP(COLLID)||'.'||STRIP(NAME) IN (
WHERE STRIP(OWNER)||'.'||STRIP(NAME) IN (
'PERPROD.CLIDUPRM',
'PERPROD.CLIINSPO',
'PERPROD.CLIPB900',
'PERPROD.CLIPLUTL',
'PERPROD.CLITGCLT',
'PERPROD.CLITRUN',
'PERPROD.CLITUCLT',
'PERPROD.CLTCOMP',
'PERPROD.CLTDBDEL',
'PERPROD.CLTOBJUP',
'PERPROD.CLTPOLCY',
'PERPROD.CDIOCHK',
'PERPROD.CDIODAT8',
'PERPROD.CDIOF07',
'PERPROD.CDIOF08',
'PERPROD.CDIOF17',
'PERPROD.CDIOO02X',
'PERPROD.CDIOSRB',
'PERPROD.CDITADRN',
'PERPROD.CDITASEQ',
'PERPROD.CDITBPTI',
'PERPROD.CDITBPTU',
'PERPROD.CDITFFID',
'PERPROD.CDITGNAC',
'PERPROD.CDITGNCU',
'PERPROD.CDITLEGL',
'PERPROD.CDITNCHA',
'PERPROD.CDITNCHG',
'PERPROD.CDITNEOT',
'PERPROD.CDITNSRT',
'PERPROD.CDITPROD',
'PERPROD.CDITREAD',
'PERPROD.CDITREF',
'PERPROD.CDITREOD',
'PERPROD.CDITREOP',
'PERPROD.CDITRESP',
'PERPROD.CDITSABS',
'PERPROD.CDITSDBS',
'PERPROD.CDITSEOH',
'PERPROD.CDITSRCH',
'PERPROD.CDITUEOT',
'PERPROD.CDITUPDT')
;


--
-- FREE PLAN
--
SELECT DISTINCT CHAR(STRIP(GETVARIABLE('SYSIBM.SSID')),4) AS SSID,
       'FREE PLAN ('||STRIP(NAME)||')'
  FROM SYSIBM.SYSPLAN
WHERE STRIP(CREATOR)||'.'||STRIP(NAME)  IN (
'PERPROD.CDIPMARA',
'PERPROD.CDIPMARB',
'PERPROD.CDIPMARI',
'PERPROD.CDITBILL',
'PERPROD.CDITEXP1',
'PERPROD.CLIPBTCH')
;

