SELECT 'DB2Q' AS SSID,'Y' AS EXIST,'DBAUTH' AS AUTH,
       GRANTEE,GRANTEDTS,
       CREATETABAUTH,CREATETSAUTH,DBADMAUTH,DBCTRLAUTH,
       DBMAINTAUTH,DISPLAYDBAUTH,DROPAUTH,IMAGCOPYAUTH,
       LOADAUTH,REORGAUTH,RECOVERDBAUTH,REPAIRAUTH,
       STARTDBAUTH,STATSAUTH,STOPAUTH
  FROM SYSIBM.SYSDBAUTH
 WHERE GRANTEE IN
('ZZADMCDF'
,'ZZADMHRI'
,'ZZAIMAP'
,'ZZAIMUS'
,'ZZAPMDB'
,'ZZAPMDT'
,'ZZAPMUS'
,'ZZARTAP'
,'ZZBCWDB'
,'ZZBMRAP'
,'ZZCATRD'
,'ZZCBRDB'
,'ZZCDIUS'
,'ZZCEIDB'
,'ZZCEIUS'
,'ZZCIABT'
,'ZZCIADB'
,'ZZCIADT'
,'ZZCIFAP'
,'ZZCIFUS'
,'ZZCISUS'
,'ZZCLIUS'
,'ZZCLRBP'
,'ZZCLRBT'
,'ZZCLRUS'
,'ZZCMSBP'
,'ZZCMSDB'
,'ZZCSAP'
,'ZZCSAT'
,'ZZCWRUS'
,'ZZDB2TEC'
,'ZZEDIABP'
,'ZZEDIAPP'
,'ZZEDIAPT'
,'ZZEDIBP'
,'ZZEDIBT'
,'ZZEISMG'
,'ZZERSBP'
,'ZZERSBT'
,'ZZESTDT'
,'ZZFRGDA'
,'ZZFRGDT'
,'ZZFRIBM'
,'ZZFRPAP'
,'ZZFRPDB'
,'ZZFRPDT'
,'ZZFRPIBM'
,'ZZFRPMG'
,'ZZFRPUS'
,'ZZGLSYS0'
,'ZZHRIAP'
,'ZZHRIDB'
,'ZZHRIUS'
,'ZZIDB2F'
,'ZZINTBP'
,'ZZINTBT'
,'ZZIPSBP'
,'ZZIPSBT'
,'ZZIPSDB'
,'ZZMADBP'
,'ZZMADBT'
,'ZZMAYAP'
,'ZZPAEUG'
,'ZZPBACPT'
,'ZZPBDEMO'
,'ZZPBDEVL'
,'ZZPBDUPD'
,'ZZPBPPRL'
,'ZZPBPROD'
,'ZZPBSUS'
,'ZZPBTEST'
,'ZZPERBP'
,'ZZPMXDC'
,'ZZPRACPT'
,'ZZPRDEMO'
,'ZZPRDEVL'
,'ZZPRDUPD'
,'ZZPRPPRL'
,'ZZPRPROD'
,'ZZPRTEST'
,'ZZPSAUDB'
,'ZZPSDCON'
,'ZZPSDEVL'
,'ZZPSDUPD'
,'ZZPSDVPD'
,'ZZPSPPRL'
,'ZZPSPROD'
,'ZZPSSYS0'
,'ZZPZMUP'
,'ZZQSTBP'
,'ZZQSTBT'
,'ZZQSTUST'
,'ZZRFPDT'
,'ZZRIDUS'
,'ZZSEAAP'
,'ZZSEAMG'
,'ZZSEAUS'
,'ZZSFRBP'
,'ZZSFRBT'
,'ZZSFRDB'
,'ZZSISBT'
,'ZZSRTEST'
,'ZZSURA1'
,'ZZSURDB'
,'ZZSURN1'
,'ZZSUR00'
,'ZZSUR01'
,'ZZSUR02'
,'ZZSUR03'
,'ZZSUR04'
,'ZZSUR05'
,'ZZSUR06'
,'ZZSUR07'
,'ZZSUR08'
,'ZZSUR09'
,'ZZSUR10'
,'ZZSUR11'
,'ZZSUR13'
,'ZZSUR14'
,'ZZSUR15'
,'ZZSUR16'
,'ZZSUR17'
,'ZZSUR18'
,'ZZSUR19'
,'ZZSUR22'
,'ZZSUR24'
,'ZZSUR26'
,'ZZSUR27'
,'ZZTALCG'
,'ZZTHAAG'
,'ZZTUSR1'
,'ZZUBSSP'
,'ZZUCSAP');
SELECT 'DB2Q' AS SSID,'Y' AS EXIST,'USERAUTH' AS AUTH,
       GRANTEE,GRANTEDTS,
       BINDADDAUTH,BSDSAUTH,CREATEDBAAUTH,CREATEDBCAUTH,
       CREATESGAUTH,DISPLAYAUTH,RECOVERAUTH,STOPALLAUTH,
       STOSPACEAUTH,SYSADMAUTH,SYSOPRAUTH,TRACEAUTH,
       MON1AUTH,MON2AUTH,CREATEALIASAUTH,SYSCTRLAUTH,
       BINDAGENTAUTH,ARCHIVEAUTH,DEBUGSESSIONAUTH,
       EXPLAINAUTH,SQLADMAUTH,SDBADMAUTH,DATAACCESSAUTH,
       ACCESSCTRLAUTH,CREATESECUREAUTH
  FROM SYSIBM.SYSUSERAUTH
 WHERE GRANTEE IN
('ZZADMCDF'
,'ZZADMHRI'
,'ZZAIMAP'
,'ZZAIMUS'
,'ZZAPMDB'
,'ZZAPMDT'
,'ZZAPMUS'
,'ZZARTAP'
,'ZZBCWDB'
,'ZZBMRAP'
,'ZZCATRD'
,'ZZCBRDB'
,'ZZCDIUS'
,'ZZCEIDB'
,'ZZCEIUS'
,'ZZCIABT'
,'ZZCIADB'
,'ZZCIADT'
,'ZZCIFAP'
,'ZZCIFUS'
,'ZZCISUS'
,'ZZCLIUS'
,'ZZCLRBP'
,'ZZCLRBT'
,'ZZCLRUS'
,'ZZCMSBP'
,'ZZCMSDB'
,'ZZCSAP'
,'ZZCSAT'
,'ZZCWRUS'
,'ZZDB2TEC'
,'ZZEDIABP'
,'ZZEDIAPP'
,'ZZEDIAPT'
,'ZZEDIBP'
,'ZZEDIBT'
,'ZZEISMG'
,'ZZERSBP'
,'ZZERSBT'
,'ZZESTDT'
,'ZZFRGDA'
,'ZZFRGDT'
,'ZZFRIBM'
,'ZZFRPAP'
,'ZZFRPDB'
,'ZZFRPDT'
,'ZZFRPIBM'
,'ZZFRPMG'
,'ZZFRPUS'
,'ZZGLSYS0'
,'ZZHRIAP'
,'ZZHRIDB'
,'ZZHRIUS'
,'ZZIDB2F'
,'ZZINTBP'
,'ZZINTBT'
,'ZZIPSBP'
,'ZZIPSBT'
,'ZZIPSDB'
,'ZZMADBP'
,'ZZMADBT'
,'ZZMAYAP'
,'ZZPAEUG'
,'ZZPBACPT'
,'ZZPBDEMO'
,'ZZPBDEVL'
,'ZZPBDUPD'
,'ZZPBPPRL'
,'ZZPBPROD'
,'ZZPBSUS'
,'ZZPBTEST'
,'ZZPERBP'
,'ZZPMXDC'
,'ZZPRACPT'
,'ZZPRDEMO'
,'ZZPRDEVL'
,'ZZPRDUPD'
,'ZZPRPPRL'
,'ZZPRPROD'
,'ZZPRTEST'
,'ZZPSAUDB'
,'ZZPSDCON'
,'ZZPSDEVL'
,'ZZPSDUPD'
,'ZZPSDVPD'
,'ZZPSPPRL'
,'ZZPSPROD'
,'ZZPSSYS0'
,'ZZPZMUP'
,'ZZQSTBP'
,'ZZQSTBT'
,'ZZQSTUST'
,'ZZRFPDT'
,'ZZRIDUS'
,'ZZSEAAP'
,'ZZSEAMG'
,'ZZSEAUS'
,'ZZSFRBP'
,'ZZSFRBT'
,'ZZSFRDB'
,'ZZSISBT'
,'ZZSRTEST'
,'ZZSURA1'
,'ZZSURDB'
,'ZZSURN1'
,'ZZSUR00'
,'ZZSUR01'
,'ZZSUR02'
,'ZZSUR03'
,'ZZSUR04'
,'ZZSUR05'
,'ZZSUR06'
,'ZZSUR07'
,'ZZSUR08'
,'ZZSUR09'
,'ZZSUR10'
,'ZZSUR11'
,'ZZSUR13'
,'ZZSUR14'
,'ZZSUR15'
,'ZZSUR16'
,'ZZSUR17'
,'ZZSUR18'
,'ZZSUR19'
,'ZZSUR22'
,'ZZSUR24'
,'ZZSUR26'
,'ZZSUR27'
,'ZZTALCG'
,'ZZTHAAG'
,'ZZTUSR1'
,'ZZUBSSP'
,'ZZUCSAP');
SELECT 'DB2Q' AS SSID,'N' AS EXIST,'DBAUTH' AS AUTH, C1
  FROM (
        SELECT 'ZZADMCDF' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZADMHRI' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAIMAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAIMUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAPMDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAPMDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAPMUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZARTAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZBCWDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZBMRAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCATRD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCBRDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCDIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCEIDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCEIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIABT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIADB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIADT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIFAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIFUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCISUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLRBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLRBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLRUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCMSBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCMSDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCSAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCSAT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCWRUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZDB2TEC' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIABP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIAPP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIAPT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEISMG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZERSBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZERSBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZESTDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRGDA' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRGDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRIBM' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPIBM' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPMG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZGLSYS0' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZHRIAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZHRIDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZHRIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIDB2F' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZINTBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZINTBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIPSBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIPSBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIPSDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZMADBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZMADBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZMAYAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPAEUG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBACPT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBDEMO' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBDEVL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBDUPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBPPRL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBPROD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBSUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBTEST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPERBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPMXDC' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRACPT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRDEMO' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRDEVL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRDUPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRPPRL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRPROD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRTEST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSAUDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDCON' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDEVL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDUPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDVPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSPPRL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSPROD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSSYS0' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPZMUP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZQSTBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZQSTBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZQSTUST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZRFPDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZRIDUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSEAAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSEAMG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSEAUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSFRBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSFRBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSFRDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSISBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSRTEST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSURA1' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSURDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSURN1' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR00' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR01' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR02' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR03' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR04' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR05' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR06' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR07' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR08' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR09' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR10' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR11' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR13' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR14' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR15' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR16' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR17' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR18' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR19' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR22' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR24' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR26' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR27' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZTALCG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZTHAAG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZTUSR1' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZUBSSP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZUCSAP' FROM SYSIBM.SYSDUMMY1 ) AS TEMP (C1)
    WHERE NOT EXISTS (
SELECT GRANTEE
  FROM SYSIBM.SYSDBAUTH
 WHERE GRANTEE = C1 )
;
SELECT 'DB2Q' AS SSID,'N' AS EXIST,'USERAUTH' AS AUTH, C1
  FROM (
        SELECT 'ZZADMCDF' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZADMHRI' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAIMAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAIMUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAPMDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAPMDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZAPMUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZARTAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZBCWDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZBMRAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCATRD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCBRDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCDIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCEIDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCEIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIABT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIADB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIADT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIFAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCIFUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCISUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLRBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLRBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCLRUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCMSBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCMSDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCSAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCSAT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZCWRUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZDB2TEC' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIABP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIAPP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIAPT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEDIBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZEISMG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZERSBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZERSBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZESTDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRGDA' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRGDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRIBM' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPIBM' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPMG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZFRPUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZGLSYS0' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZHRIAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZHRIDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZHRIUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIDB2F' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZINTBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZINTBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIPSBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIPSBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZIPSDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZMADBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZMADBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZMAYAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPAEUG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBACPT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBDEMO' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBDEVL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBDUPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBPPRL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBPROD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBSUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPBTEST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPERBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPMXDC' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRACPT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRDEMO' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRDEVL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRDUPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRPPRL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRPROD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPRTEST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSAUDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDCON' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDEVL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDUPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSDVPD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSPPRL' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSPROD' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPSSYS0' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZPZMUP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZQSTBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZQSTBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZQSTUST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZRFPDT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZRIDUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSEAAP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSEAMG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSEAUS' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSFRBP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSFRBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSFRDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSISBT' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSRTEST' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSURA1' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSURDB' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSURN1' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR00' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR01' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR02' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR03' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR04' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR05' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR06' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR07' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR08' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR09' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR10' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR11' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR13' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR14' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR15' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR16' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR17' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR18' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR19' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR22' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR24' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR26' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZSUR27' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZTALCG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZTHAAG' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZTUSR1' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZUBSSP' FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT 'ZZUCSAP' FROM SYSIBM.SYSDUMMY1 ) AS TEMP (C1)
    WHERE NOT EXISTS (
SELECT GRANTEE
  FROM SYSIBM.SYSUSERAUTH
 WHERE GRANTEE = C1 )
;
