SELECT DISTINCT B.CREATOR, B.NAME, A.GRANTEE,
  A.SELECTAUTH,A.INSERTAUTH,A.UPDATEAUTH,A.DELETEAUTH
  FROM SYSIBM.SYSTABAUTH A,
       SYSIBM.SYSTABLES B
 WHERE
 B.TYPE = 'T'
 AND B.DBNAME = 'DCDI0A07'
 AND B.CREATOR = A.SCREATOR
 AND B.NAME    = A.STNAME
 AND A.GRANTEE IN ('ZZCDIAP') --,'ZZPMXTC')
 AND (SELECTAUTH = 'Y' OR
      INSERTAUTH = 'Y' OR
      DELETEAUTH = 'Y' OR
      UPDATEAUTH = 'Y' )
;
FIM;
--SELECT B.CREATOR, B.NAME, A.GRANTEE,
--  A.SELECTAUTH,A.INSERTAUTH,A.UPDATEAUTH,A.DELETEAUTH
SELECT DISTINCT A.GRANTEE
  FROM SYSIBM.SYSTABAUTH A,
       SYSIBM.SYSTABLES B
 WHERE
 B.TYPE = 'T'
 AND B.DBNAME = 'DCDI0A07'
 AND B.CREATOR = A.SCREATOR
 AND B.NAME    = A.STNAME
 AND A.GRANTEE LIKE 'ZZ%'
 AND (SELECTAUTH = 'Y' )
UNION
SELECT DISTINCT A.GRANTEE
  FROM SYSIBM.SYSTABAUTH A,
       SYSIBM.SYSTABLES B
 WHERE
 B.TYPE = 'T'
 AND B.DBNAME = 'DCDI0A07'
 AND B.CREATOR = A.SCREATOR
 AND B.NAME    = A.STNAME
 AND A.GRANTEE LIKE 'ZZ%'
 AND (INSERTAUTH = 'Y' )
UNION
SELECT DISTINCT A.GRANTEE
  FROM SYSIBM.SYSTABAUTH A,
       SYSIBM.SYSTABLES B
 WHERE
 B.TYPE = 'T'
 AND B.DBNAME = 'DCDI0A07'
 AND B.CREATOR = A.SCREATOR
 AND B.NAME    = A.STNAME
 AND A.GRANTEE LIKE 'ZZ%'
 AND (DELETEAUTH = 'Y' )
UNION
SELECT DISTINCT A.GRANTEE
  FROM SYSIBM.SYSTABAUTH A,
       SYSIBM.SYSTABLES B
 WHERE
 B.TYPE = 'T'
 AND B.DBNAME = 'DCDI0A07'
 AND B.CREATOR = A.SCREATOR
 AND B.NAME    = A.STNAME
 AND A.GRANTEE LIKE 'ZZ%'
 AND (UPDATEAUTH = 'Y' )
--    INSERTAUTH = 'Y' OR
--    DELETEAUTH = 'Y' OR
--    UPDATEAUTH = 'Y' )
