SELECT 'LOAD DATA INDDN SYSREC00 LOG NO  REPLACE', NAME,1
  FROM SYSIBM.SYSTABLES
 WHERE DBNAME = 'DUBS0T00' AND TYPE ='T'
   AND TSNAME IN (
  'SBIS0T00'
 ,'SBSS0T00'
 ,'STXS0T00')
UNION ALL
SELECT ' INTO TABLE '||STRIP(CREATOR)||'.'||STRIP(NAME), NAME, 2
  FROM SYSIBM.SYSTABLES
 WHERE DBNAME = 'DUBS0T00' AND TYPE ='T'
   AND TSNAME IN (
  'SBIS0T00'
 ,'SBSS0T00'
 ,'STXS0T00')
 ORDER BY 2,3
