DECLARE A1A_CURSOR CURSOR FOR SELECT S1_CLM_SUB_OFF_NBR ,
S1_CLM_ATLAS_YR , S1_CLM_SEQ_NBR , S1_CSFX_ID , S1_PREM_STRA_CD ,
S1_POL_ID , S1_POL_TERM_EFF_DT , A1_SAR_TABLE_TYP , A1_BA_BK_DT ,
A1_BA_ID , A1_BA_SEQ_NBR , A1_CFA_ADM_TYP , A1_CFA_AMT , A1_CFA_AMT_TYP
, A1_CFA_BANK_CD , A1_CFA_BUREAU_CTR , A1_CFA_DEG_CD , A1_CFA_DEDSUSP_CD
 , A1_CFA_DOC_NBR , A1_CFA_ORIG_ENT_DT , A1_CFA_SS_CD , A1_CFA_SS_TAX_ID
 , A1_CFA_SS_TAX_TYP , A1_CFA_STAT_PD_CTR , A1_CFA_TRAN_TYP , A1_CFA_TYP
 , A1_CFA_VNDRLGLE_ID , A1_CFA_1099_CD , A1_CSSH_INS_TYP ,
A1_CSSH_RAC_CD , A1_CSSH_SHR_TYP , A1_FFCK_ISS_DT , A1_FFCK_TYP ,
A1_LP_DED_IMPCT_CD , A1_MNYT_TYP , A1_RCRC_DET_TYP
FROM MACT_A1_AMOUNT , MACT_S1_COMM_EMPL
WHERE A1_SAR_TABLE_TYP = 'S1' AND A1_BA_ID = S1_BA_ID AND A1_BA_BK_DT =
S1_BA_BK_DT AND A1_CFA_TYP = 'SS' AND A1_CFA_AMT ^= 0 AND
A1_CSSH_INS_TYP = 'D' AND S1_POL_ID = : H AND S1_PARR_ID <> '10798000'
ORDER BY S1_CLM_SUB_OFF_NBR , S1_CLM_ATLAS_YR , S1_CLM_SEQ_NBR ,
S1_CSFX_ID , A1_BA_BK_DT DESC
