--SELECT DISTINCT OWNER FROM SYSIBM.SYSPACKAGE;
--FIM;
SELECT 'REBIND PACKAGE('||STRIP(COLLID)||'.'||STRIP(NAME)||
     '.('||STRIP(VERSION)||'));', OWNER,CREATOR
   FROM SYSIBM.SYSPACKAGE
  WHERE -- VALID='Y'
--  AND SUBSTR(NAME,1,3) <> 'SQL'
--  AND SUBSTR(NAME,1,3) <> 'DSN'
--  AND SUBSTR(NAME,1,3) <> 'DSQ'
--  AND SUBSTR(NAME,1,3) <> 'DSD'
--  AND OWNER NOT IN ('DB2TEST')
    COLLID = 'CDI7PMSC'
    ;
UNION ALL
SELECT 'REBIND PLAN('||STRIP(NAME)||');'
   FROM SYSIBM.SYSPLAN
  WHERE VALID='Y'
--  AND SUBSTR(NAME,1,3) <> 'SQL'
--  AND SUBSTR(NAME,1,3) <> 'DSN'
--  AND SUBSTR(NAME,1,3) <> 'DSQ'
--  AND SUBSTR(NAME,1,3) <> 'DSD'
    AND QUALIFIER LIKE '%PROD'
