SELECT 'REBIND PACKAGE('||STRIP(COLLID)||'.'||STRIP(NAME)||
     '.('||STRIP(VERSION)||'));'
   FROM SYSIBM.SYSPACKAGE
  WHERE VALID='Y'
--  AND SUBSTR(NAME,1,3) <> 'SQL'
--  AND SUBSTR(NAME,1,3) <> 'DSN'
--  AND SUBSTR(NAME,1,3) <> 'DSQ'
--  AND SUBSTR(NAME,1,3) <> 'DSD'
    AND OWNER NOT IN ('DB2PROD')
UNION ALL
SELECT 'REBIND PLAN('||STRIP(NAME)||');'
   FROM SYSIBM.SYSPLAN
  WHERE VALID='Y'
--  AND SUBSTR(NAME,1,3) <> 'SQL'
--  AND SUBSTR(NAME,1,3) <> 'DSN'
--  AND SUBSTR(NAME,1,3) <> 'DSQ'
--  AND SUBSTR(NAME,1,3) <> 'DSD'
    AND QUALIFIER LIKE '%PROD'
