--
  SET CURRENT SQLID='DBA1ADM';
--
  CREATE TABLESPACE TEST0
    IN DDBA0T00
    USING STOGROUP GDAP0T00
    PRIQTY 50000 SECQTY 36000
    ERASE  NO
    FREEPAGE 0 PCTFREE 0
    GBPCACHE CHANGED
    TRACKMOD YES
    SEGSIZE 4
    BUFFERPOOL BP1
    LOCKSIZE ANY
    LOCKMAX SYSTEM
    CLOSE NO
    COMPRESS YES
    CCSID      EBCDIC
    DEFINE YES
    MAXROWS 255;
--
  COMMIT;
--
----------------------------------------------------------------------- -
--    Table=DBA1ADM.TEST0 In DDBA0T00.TEST0
----------------------------------------------------------------------- -
--
  CREATE TABLE DBA1ADM.TEST0
     (S3_SAR_TABLE_TYP     CHAR(2) FOR SBCS DATA NOT NULL,
      S3_BA_ID             CHAR(11) FOR SBCS DATA NOT NULL,
      S3_BA_SEQ_NBR        DECIMAL(5, 0) NOT NULL,
      S3_BA_BK_DT          CHAR(6) FOR SBCS DATA NOT NULL,
      S3_BAI_TYP           CHAR(4) FOR SBCS DATA NOT NULL,
      S3_UBA_END_RSN_CD    CHAR(3) FOR SBCS DATA NOT NULL,
      S3_UBA_RSN_CD        CHAR(7) FOR SBCS DATA NOT NULL,
      S3_UBA_TERMN_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_UBA_TYP           CHAR(3) FOR SBCS DATA NOT NULL,
      S3_CAGE_EVAL_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PARR_ID           CHAR(8) FOR SBCS DATA NOT NULL,
      S3_POL_AGN_BLL_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_BILL_SYS_CD   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_BND_ID_CD     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_BOND_RNW_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_CAG_ID        CHAR(8) FOR SBCS DATA NOT NULL,
      S3_POL_COVP_CD       CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_EMPACCT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_EXCESS_TYP    CHAR(2) FOR SBCS DATA NOT NULL,
      S3_POL_EXP_CD        CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_FF_ISEG_CD    CHAR(2) FOR SBCS DATA NOT NULL,
      S3_POL_FFMP_CD       CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_HQ_ST_CD      CHAR(2) FOR SBCS DATA NOT NULL,
      S3_POL_ID            CHAR(11) FOR SBCS DATA NOT NULL,
      S3_POL_IN_CLMMD_DT   CHAR(6) FOR SBCS DATA NOT NULL,
      S3_POL_INSD_NM_TXT   CHAR(70) FOR SBCS DATA NOT NULL,
      S3_POL_INTSTT_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_INVP_TYP      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_INVPJURS_ID   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_LG_ACCT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_MAP_CD        CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_MAP_JURS_ID   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_MKTG_ID       CHAR(6) FOR SBCS DATA NOT NULL,
      S3_POL_MR_PT_NBR     CHAR(2) FOR SBCS DATA NOT NULL,
      S3_POL_MR_RNG_CD     CHAR(2) FOR SBCS DATA NOT NULL,
      S3_POL_NEW_ENT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_NEW_RNW_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_NI_LGLE_ID    CHAR(11) FOR SBCS DATA NOT NULL,
      S3_POL_NTL_TM_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_ORG_INCP_DT   DATE WITH DEFAULT NULL,
      S3_POL_POA_LVL_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_PR_PFX_CD     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_POL_PR_PREM_AMT   DECIMAL(9, 0) NOT NULL,
      S3_POL_RETRO_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_RGN_TM_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_RISK_ID       CHAR(3) FOR SBCS DATA NOT NULL,
      S3_POL_SIC_CD        CHAR(5) FOR SBCS DATA NOT NULL,
      S3_POL_SIC_DIV_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_SRCE_CD       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_SRD_BOB_CD    CHAR(2) FOR SBCS DATA NOT NULL,
      S3_POL_SRD_UG_CD     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_SRD_UGDT_CD   CHAR(3) FOR SBCS DATA NOT NULL,
      S3_POL_SUBCESS_TYP   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_SVC_RSK_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_TERM_EFF_DT   DATE WITH DEFAULT NULL,
      S3_POL_TERM_EXP_DT   DATE WITH DEFAULT NULL,
      S3_POL_TM_SZ_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_TYPCONTR_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POL_UWPGM_CD      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_POL_VNDRLGLE_ID   CHAR(11) FOR SBCS DATA NOT NULL,
      S3_POL_VTG_YR        CHAR(4) FOR SBCS DATA NOT NULL,
      S3_POL_XS_LAYER_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_POLP_PA_ORGU_ID   CHAR(6) FOR SBCS DATA NOT NULL,
      S3_POLP_RJ_ORGU_ID   CHAR(6) FOR SBCS DATA NOT NULL,
      S3_BED_FININST_TYP   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_BED_NONPROF_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CD_CERT_DEC_ID    CHAR(10) FOR SBCS DATA NOT NULL,
      S3_CGL_TYP           CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_AUD_EFF_DT   CHAR(6) FOR SBCS DATA NOT NULL,
      S3_CSAR_AUD_EXP_DT   CHAR(6) FOR SBCS DATA NOT NULL,
      S3_CSAR_BENSTR_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_BIND_TYP     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_CSAR_BLKENT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_CNCL_DT      DATE WITH DEFAULT NULL,
      S3_CSAR_COVC_CD      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_COVP_CD      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_CVV_CD       CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_DEDPGM_TYP   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_DEVRAT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_EFF_DT       DATE WITH DEFAULT NULL,
      S3_CSAR_EXP_DT       DATE WITH DEFAULT NULL,
      S3_CSAR_GRADCOM_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_CSAR_HILO_IND     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_INVC_DT      DATE WITH DEFAULT NULL,
      S3_CSAR_LRGDED_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_LTD_CD_TYP   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_MAJ_LN_CD    CHAR(2) FOR SBCS DATA NOT NULL,
      S3_CSAR_MIN_LN_CD    CHAR(2) FOR SBCS DATA NOT NULL,
      S3_CSAR_MCOFF_CD     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_CSAR_JURS_ID      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_NEW_RNW_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_NSTT_IND     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_OTH_COV_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_PCOV_TYP     CHAR(2) FOR SBCS DATA NOT NULL,
      S3_CSAR_PHDP_CD      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_PHDP_TYP     CHAR(4) FOR SBCS DATA NOT NULL,
      S3_CSAR_RATETYP_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_RETRO_CD     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_RETRO_DT     DATE WITH DEFAULT NULL,
      S3_CSAR_RPFORM_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_RTGP_CD      CHAR(6) FOR SBCS DATA NOT NULL,
      S3_CSAR_TRM_BEG_DT   DATE WITH DEFAULT NULL,
      S3_CSAR_TRM_END_DT   DATE WITH DEFAULT NULL,
      S3_CSAR_TXN_CT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_TXN_EFF_DT   DATE WITH DEFAULT NULL,
      S3_CSAR_XEQK_IND     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_XEXPL_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_XSPL_IND     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_XTHFT_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_XVNDL_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CSAR_XWIND_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_DLD_ANEST_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_DLD_DENTBD_CD     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_DLD_SPCL_CD       CHAR(2) FOR SBCS DATA NOT NULL,
      S3_DLD_SURGICAL_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_ESTT_LIMIT_CD     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_ESTT_LIMIT_CD2    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_ESTT_POA_RNG_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_ESTT_POARNG_CD2   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_ESTT_TRTY_ID      CHAR(6) FOR SBCS DATA NOT NULL,
      S3_ESTT_TRTY_ID2     CHAR(6) FOR SBCS DATA NOT NULL,
      S3_FEMP_ADJ_RT_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_FEMP_RNG_CD       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_FEMP_TYP          CHAR(1) FOR SBCS DATA NOT NULL,
      S3_FRF_CD            CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PC_ALARM_FCTR     DECIMAL(7, 4) NOT NULL,
      S3_PC_ARSURCH_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_COMPDEV_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_FIREBR_FCTR    DECIMAL(7, 4) NOT NULL,
      S3_PC_FLATCHG_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_MRTRTGP_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_RATEDPT_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_RATEMOD_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_SCHED_FCTR     DECIMAL(7, 4) NOT NULL,
      S3_PC_SGMNTL_FCTR    DECIMAL(7, 4) NOT NULL,
      S3_PC_SIZERSK_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_TXCERT_FCTR    DECIMAL(7, 4) NOT NULL,
      S3_PC_XPERMOD_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PC_XPNSMOD_FCTR   DECIMAL(7, 4) NOT NULL,
      S3_PHPC_DIV_YR_NBR   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PHPC_DIVTRM_NBR   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PHPC_LCF_FCTR     DECIMAL(7, 4) NOT NULL,
      S3_PHPC_VALU_NBR     CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PLOC_AREA_CD      CHAR(6) FOR SBCS DATA NOT NULL,
      S3_PLOC_AREA_CD2     CHAR(6) FOR SBCS DATA NOT NULL,
      S3_PLOC_AREA_CD3     CHAR(6) FOR SBCS DATA NOT NULL,
      S3_PLOC_ATYP_CD      CHAR(6) FOR SBCS DATA NOT NULL,
      S3_PLOC_ATYP_CD2     CHAR(6) FOR SBCS DATA NOT NULL,
      S3_PLOC_ATYP_CD3     CHAR(6) FOR SBCS DATA NOT NULL,
      S3_PLOC_CANP_CD      CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PLOC_CTRY_CD      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_PLOC_ST_CD        CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PLOC_ZIP_CD       CHAR(9) FOR SBCS DATA NOT NULL,
      S3_PREM_COFF_CD      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_PREM_COMM_AMT     DECIMAL(11, 2) NOT NULL,
      S3_PREM_EFF_DT       DATE WITH DEFAULT NULL,
      S3_PREM_EST_IND      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PREM_EXP_DT       DATE WITH DEFAULT NULL,
      S3_PREM_FACLTV_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PREM_INS_TYP      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PREM_MARKOFF_DT   DATE WITH DEFAULT NULL,
      S3_PREM_PAYPFRQ_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PREM_PAYP_CD      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_PREM_POA_RNG_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PREM_PT_CD        CHAR(5) FOR SBCS DATA NOT NULL,
      S3_PREM_RAC_CD       CHAR(8) FOR SBCS DATA NOT NULL,
      S3_PREM_REINS_TYP    CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PREM_RETRO_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PREM_SHR_TYP      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PREM_SSRC_CD      CHAR(5) FOR SBCS DATA NOT NULL,
      S3_PREM_SSRC_TYP     CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PREM_STRA_CD      CHAR(2) FOR SBCS DATA NOT NULL,
      S3_PREM_TYP          CHAR(3) FOR SBCS DATA NOT NULL,
      S3_PREM_WRTN_AMT     DECIMAL(11, 2) NOT NULL,
      S3_PUBE_TYP          CHAR(2) FOR SBCS DATA NOT NULL,
      S3_RA_COV_NOTE_ID    CHAR(15) FOR SBCS DATA NOT NULL,
      S3_SAI_EXT_COV_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_SAI_TYP           CHAR(3) FOR SBCS DATA NOT NULL,
      S3_SAR_AUD_FRQ_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_SAR_HST_PROT_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_SAR_IM_SCHD_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_SAR_PKGP_CD       CHAR(4) FOR SBCS DATA NOT NULL,
      S3_SAR_PUB_PROT_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_SAR_TYP           CHAR(4) FOR SBCS DATA NOT NULL,
      S3_SARR_RTD_NBR      DECIMAL(15, 2) NOT NULL,
      S3_SARR_TRSPGM_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_SARR_UNIT_TYP     CHAR(8) FOR SBCS DATA NOT NULL,
      S3_UISR_PRIMARY_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_UISR_TYP          CHAR(2) FOR SBCS DATA NOT NULL,
      S3_ULYL_MFG_BW_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_ULYL_MFG_PTW_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_ULYL_POA_RNG_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_CGLP_BIPD_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_CLM_BAS_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_CRSP_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_MED_CD       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_TAIL_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_VER_CD       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_WWIDE_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CGLP_XRPTEXP_DT   CHAR(8) FOR SBCS DATA NOT NULL,
      S3_CLR_ABC_CD        CHAR(5) FOR SBCS DATA NOT NULL,
      S3_CGL_CGLC_CD       CHAR(5) FOR SBCS DATA NOT NULL,
      S3_CGL_ESRC_CD       CHAR(2) FOR SBCS DATA NOT NULL,
      S3_CGL_IMC_CD        CHAR(6) FOR SBCS DATA NOT NULL,
      S3_CLR_POOL_IND      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_CLR_TBOP_CD       CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_LSPCTRNG_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_LMT_LSSPART_PCT   DECIMAL(5, 4) NOT NULL,
      S3_STK_AGE_RNG_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_STK_CONST_CD      CHAR(2) FOR SBCS DATA NOT NULL,
      S3_STK_CONTENTS_CD   CHAR(2) FOR SBCS DATA NOT NULL,
      S3_STK_CORROS_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_STK_PSGO_LK_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_STK_PSGO_OF_IND   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_STK_PUMP_SYS_CD   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_STK_UNDER_IND     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_BA_ENTRY_SYS_CD   CHAR(3) FOR SBCS DATA NOT NULL,
      S3_BA_PREV_ID        CHAR(11) FOR SBCS DATA NOT NULL,
      S3_BA_PREV_SEQ_NBR   DECIMAL(5, 0) NOT NULL,
      S3_BA_SRCE_STR_ID    CHAR(9) FOR SBCS DATA NOT NULL,
      S3_SSD_SFIL_ID       CHAR(17) FOR SBCS DATA NOT NULL,
      S3_SSD_PRCS_PER_YR   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_DED_DEDC_CD       CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_LDAP_CD       CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_AMT           DECIMAL(11, 2) NOT NULL,
      S3_DED_AMT_RNG_CD    CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_CAP_AMT       DECIMAL(9, 0) NOT NULL,
      S3_DED_COVC_CD       CHAR(4) FOR SBCS DATA NOT NULL,
      S3_DED_LEXP_TYP      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_METH_TYP      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_MIN_AMT       DECIMAL(11, 0) NOT NULL,
      S3_DED_PCT           DECIMAL(7, 4) NOT NULL,
      S3_DED_PCT_RNG_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_DED_POA_IND       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_DED_DEDC_CD2      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_LDAP_CD2      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_AMT2          DECIMAL(11, 2) NOT NULL,
      S3_DED_AMT_RNG_CD2   CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_CAP_AMT2      DECIMAL(9, 0) NOT NULL,
      S3_DED_COVC_CD2      CHAR(4) FOR SBCS DATA NOT NULL,
      S3_DED_LEXP_TYP2     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_METH_TYP2     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_DED_MIN_AMT2      DECIMAL(11, 0) NOT NULL,
      S3_DED_PCT2          DECIMAL(7, 4) NOT NULL,
      S3_DED_PCT_RNG_CD2   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_DED_POA_IND2      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_LMTC_CD       CHAR(5) FOR SBCS DATA NOT NULL,
      S3_LMT_LDAP_CD       CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_AMT           DECIMAL(11, 2) NOT NULL,
      S3_LMT_AMT_RNG_CD    CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_CMPN_BD_CD    CHAR(5) FOR SBCS DATA NOT NULL,
      S3_LMT_DFNS_CST_CD   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_LMT_STACK_CD      CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_SUBLMT_IND    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_VALU_TYP      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_XS_IND        CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_XSPCTRG_CD    CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_LMTC_CD2      CHAR(5) FOR SBCS DATA NOT NULL,
      S3_LMT_LDAP_CD2      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_AMT2          DECIMAL(11, 2) NOT NULL,
      S3_LMT_AMT_RNG_CD2   CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_CMPN_BD_CD2   CHAR(5) FOR SBCS DATA NOT NULL,
      S3_LMT_DFNSCST_CD2   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_LMT_STACK_CD2     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_SUBLMT_IND2   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_VALU_TYP2     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_XS_IND2       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_XSPCTRG_CD2   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_LMTC_CD3      CHAR(5) FOR SBCS DATA NOT NULL,
      S3_LMT_LDAP_CD3      CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_AMT3          DECIMAL(11, 2) NOT NULL,
      S3_LMT_AMT_RNG_CD3   CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_CMPN_BD_CD3   CHAR(5) FOR SBCS DATA NOT NULL,
      S3_LMT_DFNSCST_CD3   CHAR(4) FOR SBCS DATA NOT NULL,
      S3_LMT_STACK_CD3     CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_SUBLMT_IND3   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_VALU_TYP3     CHAR(3) FOR SBCS DATA NOT NULL,
      S3_LMT_XS_IND3       CHAR(1) FOR SBCS DATA NOT NULL,
      S3_LMT_XSPCTRG_CD3   CHAR(1) FOR SBCS DATA NOT NULL,
      S3_PC_LCM_FCTR       DECIMAL(7, 4) NOT NULL WITH DEFAULT,
      S3_PC_LCM_EFF_DT     DATE WITH DEFAULT NULL,
      S3_SARR_ADDRTD_NBR   DECIMAL(15, 2) NOT NULL WITH DEFAULT,
      S3_SARR_ADDUNT_TYP   CHAR(8) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_POL_PRIM_PFX_CD   CHAR(3) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_POL_PRIM_NBR      CHAR(8) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_MOLD_CD      CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_XLEAD_IND    CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_XTRSM_IND    CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CGL_CGLSC_CD      CHAR(2) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_POL_PR_POL_ID     CHAR(11) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_TRSM_CD      CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_TRSMHZD_CD   CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_POL_TRSMHZD_CD    CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CGL_RPG_CD        CHAR(2) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_LMTC_CD4      CHAR(5) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_LDAP_CD4      CHAR(3) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_AMT4          DECIMAL(11, 2) NOT NULL WITH DEFAULT,
      S3_LMT_AMT_RNG_CD4   CHAR(3) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_CMPN_BD_CD4   CHAR(5) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_DFNSCST_CD4   CHAR(4) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_STACK_CD4     CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_SUBLMT_IND4   CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_VALU_TYP4     CHAR(3) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_XS_IND4       CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_LMT_XSPCTRG_CD4   CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_FFIUNT_NBR   CHAR(3) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_CSAR_FFISEQ_NBR   CHAR(2) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
      S3_RATC_POA_AMT      DECIMAL(11, 0) NOT NULL WITH DEFAULT,
      S3_POL_XTRSMX_IND    CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT)
    IN DDBA0T00.TEST0
    AUDIT NONE
    DATA CAPTURE NONE
    CCSID      EBCDIC
    NOT VOLATILE;
--
  COMMIT;
--
----------------------------------------------------------------------- -
-- Database=DDBA0T00
--    Index=DBA1ADM.IXTEST0 On DBA1ADM.TEST0
----------------------------------------------------------------------- -
--
  CREATE UNIQUE INDEX DBA1ADM.IXTEST0
    ON DBA1ADM.TEST0
     (S3_BA_BK_DT           ASC,
      S3_BA_ID              ASC,
      S3_BA_SEQ_NBR         ASC)
    USING STOGROUP GDAP0T00
    PRIQTY 46800 SECQTY 7200
    ERASE  NO
    FREEPAGE 0 PCTFREE 0
    GBPCACHE CHANGED
    CLUSTER
    BUFFERPOOL BP2
    CLOSE NO
    COPY NO
    DEFINE YES
    PIECESIZE 2 G;
--
  COMMIT;
--
----------------------------------------------------------------------- -
-- ADB2GEN - End of generated DDL                                     - -
----------------------------------------------------------------------- -
--
