--
  SET CURRENT SQLID='DBA1ADM';
--
  CREATE TABLESPACE TEST3
    IN DDBA0T00
    USING STOGROUP GDAP0T00
    PRIQTY 48    SECQTY 48
    SEGSIZE 4
    BUFFERPOOL BP1
    LOCKSIZE ANY
    LOCKMAX SYSTEM
    CCSID      EBCDIC
    DEFINE YES
    MAXROWS 255;
--
  COMMIT;
--
----------------------------------------------------------------------- -
--    TABLE=DBA1ADM.TEST0 IN DDBA0T00.TEST0
----------------------------------------------------------------------- -
--
  CREATE TABLE DBA1ADM.TEST3
     (CUSTID               INTEGER NOT NULL WITH DEFAULT,
      PRICE                DECIMAL(12,4) NOT NULL WITH DEFAULT)
    IN DDBA0T00.TEST3
    AUDIT NONE
    DATA CAPTURE NONE
    CCSID      EBCDIC
    NOT VOLATILE;
--
  COMMIT;
--
  INSERT INTO DBA1ADM.TEST3 VALUES (1, 1.00);
  INSERT INTO DBA1ADM.TEST3 VALUES (2, 2.50);
  INSERT INTO DBA1ADM.TEST3 VALUES (3, 3.99);
  INSERT INTO DBA1ADM.TEST3 VALUES (4, 4.15);
  COMMIT;
