SELECT
B.DBNAME, B.TSNAME,
--STRIP(B.CREATOR)||'.'||STRIP(B.NAME),
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(A.DBNAME)||'.'||STRIP(A.TSNAME)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END AS DSNAME
,A.PARTITION
,CASE WHEN A.COMPRESS <> 'Y' THEN 'N'
      ELSE A.COMPRESS
 END AS COMPRESS
,'S' AS TYPE, A.DSNUM, A.EXTENTS
  FROM SYSIBM.SYSTABLEPART A,
       SYSIBM.SYSTABLES B
 WHERE B.TYPE = 'T'
   AND B.DBNAME = A.DBNAME
   AND B.TSNAME = A.TSNAME
   AND B.CREATOR ='FINPROD'                                             00140003
UNION ALL
SELECT
B.CREATOR,B.NAME,
--STRIP(B.CREATOR)||'.'||STRIP(B.NAME),
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(B.DBNAME)||'.'||
STRIP(B.INDEXSPACE)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END AS DSNAME
,A.PARTITION, 'N' AS COMPRESS, 'X' AS TYPE, A.DSNUM, A.EXTENTS
  FROM SYSIBM.SYSINDEXPART A,
       SYSIBM.SYSINDEXES B,
       SYSIBM.SYSTABLES  C
 WHERE A.IXNAME = B.NAME
   AND A.IXCREATOR = B.CREATOR
   AND C.TYPE = 'T'
   AND B.TBNAME = C.NAME
   AND B.TBCREATOR = C.CREATOR
   AND C.CREATOR ='FINPROD'                                             00140003
 ORDER BY 1, 3
;
