SELECT 'DB2H' AS SSID,
STRIP(VCATNAME)||'.DSNDBD.'||STRIP(DBNAME)||'.'||STRIP(TSNAME)||
'.'||STRIP(IPREFIX)||'0001.A'||
            CASE WHEN PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(PARTITION),3,3)
            END AS VSAM
  FROM SYSIBM.SYSTABLEPART
UNION ALL
SELECT 'DB2H' AS SSID,
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(B.DBNAME)||'.'||
STRIP(B.INDEXSPACE)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END AS VSAM
 FROM SYSIBM.SYSINDEXPART A,
       SYSIBM.SYSINDEXES B
 WHERE A.IXNAME = B.NAME
   AND A.IXCREATOR = B.CREATOR
;
