SELECT
'CDIDE.DSNDBD.'||DBNAME||'.'||TSNAME
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'PERPROD'
AND NAME IN ('CLT_ADR_RELATION'
            ,'CLIENT_ADDRESS'
            ,'CLIENT_TAB'
            ,'CLT_CLT_RELATION'
            ,'INDIVIDUAL_CLIENT'
            ,'CLIENT_LICENSE'
            ,'CLT_OTHER_OBJECTS'
            ,'CLT_OBJ_RELATION'
            ,'CLIENT_PHONE'
            ,'CLIENT_POLICY'
            ,'CLFT_POLICY_TERM')
;
FIM;
SELECT
'CDIDE.DSNDBD.'||DBNAME||'.'||TSNAME
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'FINPROD'
AND NAME IN ('CLT_ADD_ADR_TEXT'
            ,'CLT_ADD_NAME_TEXT'
            ,'CLT_ADR_RELATION'
            ,'BUSINESS_CLIENT'
            ,'CLT_OTHER_OBJECTS'
            ,'CLT_OBJ_RELATION'
            ,'CLIENT_ADDRESS'
            ,'CLIENT_BILLING'
            ,'CLIENT_CLAIM'
            ,'CLIENT_HELP'
            ,'CLIENT_KEYS'
            ,'CLIENT_MENU'
            ,'CLIENT_POLICY'
            ,'CLIENT_CROSS_REF'
            ,'CLIENT_SUMMARY'
            ,'CLIENT_UCT'
            ,'CLT_CLT_RELATION'
            ,'CLT_FORMAT_CLIENTS'
            ,'CLT_FORMAT_NAME'
            ,'HOUSEHOLD_CLIENT'
            ,'INDIVIDUAL_CLIENT'
            ,'CLT_CONTACT_INFO'
            ,'CLIENT_LICENSE'
            ,'CLUB_MEM_INFO'
            ,'CLT_OWNING_SYSTEM'
            ,'CLIENT_PHONE'
            ,'CLT_REF_RELATION'
            ,'CLT_TEMPLATE'
            ,'CLIENT_TAX'
            ,'CLT_CLT_VLD_REL'
            ,'CDIT_CLT_RELATIONS'
            ,'CLT_TABLE_ID_GEN'
            ,'CDIT_MRG_STATUS'
            ,'CLIENT_TAB'
            ,'CDIT_NAME_ADDRESS'
            ,'CDIT_AGREEMENT'
            ,'CDIT_NA_ADDRESS'
            ,'CDIT_NA_BUS_ENTITY'
            ,'CDIT_NA_NAME'
            ,'CDIT_NA_PRDCR_REF'
            ,'CDIT_POL_NA_INVL'
            ,'CDIT_POL_SECTION'
            ,'CDIT_PL_DEPT_REF'
            ,'CDIT_REF_PRODUCT'
            ,'CLT_TABLE_EPIC_GEN'
            ,'CLT_ADR_SEARCH')
