SELECT 'DB2P' AS SSID,
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(A.DBNAME)||'.'||STRIP(A.TSNAME)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END AS VSAM
       ,A.SPACEF,A.EXTENTS, A.DSNUM
  FROM SYSIBM.SYSTABLEPART A,
       SYSIBM.SYSTABLESPACE B
 WHERE A.TSNAME = B.NAME
   AND A.DBNAME = B.DBNAME
;
FIM;
UNION ALL
SELECT 'DB2P' AS SSID,
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(B.DBNAME)||'.'||
STRIP(B.INDEXSPACE)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END AS VSAM
 FROM SYSIBM.SYSINDEXPART A,
       SYSIBM.SYSINDEXES B
 WHERE A.IXNAME = B.NAME
   AND A.IXCREATOR = B.CREATOR
;
