SELECT
STRIP(A.DBNAME)||'.'||STRIP(A.TSNAME),
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(A.DBNAME)||'.'||STRIP(A.TSNAME)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END
,A.PARTITION, A.COMPRESS, 'S' AS TYPE, A.DSNUM, A.EXTENTS
  FROM SYSIBM.SYSTABLEPART A,
       SYSIBM.SYSTABLES B
 WHERE B.TYPE = 'T'
   AND B.DBNAME = A.DBNAME
   AND B.TSNAME = A.TSNAME
-- AND B.CREATOR = 'PERPROD'
-- AND A.VCATNAME = 'MAPDE'
UNION ALL
SELECT
STRIP(B.CREATOR)||'.'||STRIP(B.NAME),
STRIP(A.VCATNAME)||'.DSNDBD.'||STRIP(B.DBNAME)||'.'||
STRIP(B.INDEXSPACE)||
'.'||STRIP(A.IPREFIX)||'0001.A'||
            CASE WHEN A.PARTITION = 0 THEN '001'
                 ELSE SUBSTR(DIGITS(A.PARTITION),3,3)
            END
,A.PARTITION, ' ', 'X' AS TYPE, A.DSNUM, A.EXTENTS
  FROM SYSIBM.SYSINDEXPART A,
       SYSIBM.SYSINDEXES B,
       SYSIBM.SYSTABLES  C
 WHERE A.IXNAME = B.NAME
   AND A.IXCREATOR = B.CREATOR
   AND C.TYPE = 'T'
   AND B.TBNAME = C.NAME
   AND B.TBCREATOR = C.CREATOR
-- AND C.CREATOR = 'PERPROD'
-- AND A.VCATNAME = 'MAPDE'
 ORDER BY 1, 3
;
